import { useState } from "react";
import { base44 } from "@/api/base44Client";
import { Save, Download, Send, ShieldCheck, Loader2 } from "lucide-react";
import { downloadBillOfSalePdf } from "@/lib/billOfSalePdf";
export default function DraftActions({ draft, save, saving }) {
  const [sending, setSending] = useState(false), [message, setMessage] = useState("");
  const blocked = draft.warnings.some((w) => w.severity === "critical" && w.id !== "co_owner_missing_signature") || !draft.price_confirmed || !draft.sale_date_confirmed || !draft.purchaser_name_confirmed || !draft.user_reviewed;
  const sendReview = async () => { setSending(true); setMessage(""); try { const saved = await save(); const recipients = [...new Set([saved.purchaser_email, saved.seller_email].filter(Boolean))]; if (!recipients.length) { setMessage("Add a buyer or seller email first."); return; } const url = `${window.location.origin}/bill-of-sale?draft_id=${saved.id}`; await Promise.all(recipients.map((to) => base44.integrations.Core.SendEmail({ to, subject: `FAA Bill of Sale draft — N${saved.registration_number || ""}`, body: `An FAA Aircraft Bill of Sale review draft is ready. Review it here: ${url}\n\nSignatures are intentionally blank and must be provided manually.` }))); setMessage(`Review sent to ${recipients.length} recipient(s).`); } catch (e) { setMessage(e.message || "Review email could not be sent."); } finally { setSending(false); } };
  return <div className="sticky bottom-4 z-20 flex flex-wrap items-center gap-2 rounded-2xl border border-border bg-card/95 p-3 shadow-xl backdrop-blur"><button onClick={() => save()} disabled={saving} className="inline-flex min-h-11 items-center gap-2 rounded-xl border border-border px-4 text-sm font-bold text-card-foreground">{saving ? <Loader2 className="h-4 w-4 animate-spin" /> : <Save className="h-4 w-4" />} Save draft</button><button onClick={() => downloadBillOfSalePdf(draft)} className="inline-flex min-h-11 items-center gap-2 rounded-xl border border-border px-4 text-sm font-bold text-card-foreground"><Download className="h-4 w-4" /> PDF draft</button><button onClick={sendReview} disabled={sending} className="inline-flex min-h-11 items-center gap-2 rounded-xl border border-border px-4 text-sm font-bold text-card-foreground">{sending ? <Loader2 className="h-4 w-4 animate-spin" /> : <Send className="h-4 w-4" />} Send for review</button><button onClick={() => save("ready_for_signature")} disabled={blocked || saving} title={blocked ? "Resolve critical warnings and complete confirmations first" : ""} className="ml-auto inline-flex min-h-11 items-center gap-2 rounded-xl bg-primary px-4 text-sm font-bold text-primary-foreground disabled:opacity-40"><ShieldCheck className="h-4 w-4" /> Ready for signature</button>{message && <p className="w-full text-xs text-muted-foreground">{message}</p>}</div>;
}