// Escrow configuration & shared helpers
export const ESCROW_STATUS = {
  draft:            { label: "Draft",             color: "#AAA49C", bg: "rgba(0,0,0,0.05)",       order: 0 },
  contract_sent:    { label: "Contract Sent",     color: "#185FA5", bg: "rgba(24,95,165,0.08)",   order: 1 },
  contract_signed:  { label: "Contract Signed",   color: "#0B2D5B", bg: "rgba(11,45,91,0.10)",    order: 2 },
  funds_pending:    { label: "Funds Pending",     color: "#A67C00", bg: "rgba(212,160,23,0.10)",  order: 3 },
  funds_secured:    { label: "Funds Secured",     color: "#0F7A56", bg: "rgba(15,122,86,0.10)",   order: 4 },
  inspection:       { label: "In Inspection",     color: "#E8A83A", bg: "rgba(232,168,58,0.12)",  order: 5 },
  released:         { label: "Released",          color: "#0F7A56", bg: "rgba(15,122,86,0.12)",   order: 6 },
  closed:           { label: "Closed · Paid",     color: "#0F7A56", bg: "rgba(15,122,86,0.16)",   order: 7 },
  cancelled:        { label: "Cancelled",         color: "#6B6560", bg: "rgba(0,0,0,0.05)",       order: 8 },
  disputed:         { label: "Disputed",          color: "#C0392B", bg: "rgba(192,57,43,0.08)",   order: 9 },
};

export const STATUS_FLOW = [
  "draft", "contract_sent", "contract_signed", "funds_pending",
  "funds_secured", "inspection", "released", "closed",
];

export function calcFinderFee(saleAmount, feePct) {
  const amt = Number(saleAmount) || 0;
  const pct = Number(feePct) || 0;
  const fee = Math.round(amt * pct) / 100;
  return { fee, net: Math.max(0, amt - fee) };
}

export function formatMoney(amount, currency = "USD") {
  if (amount == null || isNaN(amount)) return "—";
  return new Intl.NumberFormat("en-US", {
    style: "currency", currency, maximumFractionDigits: 0,
  }).format(amount);
}

export function buildContractText(tx) {
  const { fee, net } = calcFinderFee(tx.sale_amount, tx.finders_fee_pct);
  const today = new Date().toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" });
  return `HUSTLE CONTRACT · AVIATION INTRAZONE
Date: ${today}

AIRCRAFT: ${tx.aircraft_label || "—"}

PARTIES
  Buyer:  ${tx.buyer_name || "—"} <${tx.buyer_email || "—"}>
  Seller: ${tx.seller_name || "—"} <${tx.seller_email || "—"}>
  Broker: ${tx.broker_name || "—"} <${tx.broker_email || "—"}>

FINANCIAL TERMS
  Agreed Sale Amount:   ${formatMoney(tx.sale_amount, tx.currency)}
  Finder's Fee (${tx.finders_fee_pct || 0}%): ${formatMoney(fee, tx.currency)}
  Seller Net Proceeds:  ${formatMoney(net, tx.currency)}

ESCROW TERMS
  Provider:           ${tx.escrow_provider === "escrow_com" ? "Escrow.com" : "Internal Escrow"}
  Inspection Period:  ${tx.inspection_period_days || 3} days

TRANSPARENCY CLAUSE
  All parties acknowledge the finder's fee % is fully transparent and locked in
  upon signing. On successful closing of the transaction, the escrow agent will
  release the finder's fee directly to the Broker listed above, and the seller
  net amount to the Seller. No party may reduce or re-negotiate the fee after
  this contract is signed without written consent of all three parties.

GOVERNING LAW & JURISDICTION
  This Agreement shall be governed by and construed in accordance with the laws
  of the Czech Republic, without regard to its conflict of law provisions. Any
  disputes arising out of or in connection with this Agreement that cannot be
  resolved by mutual negotiation within 30 days shall be submitted to the
  exclusive jurisdiction of the competent courts of Prague, Czech Republic. For
  EU consumers, the right to bring proceedings before the courts of the member
  state of habitual residence is not affected.

SIGNATURES
  Buyer:  _________________________   Date: __________
  Seller: _________________________   Date: __________
  Broker: _________________________   Date: __________

ABOS HustlContract™ · Version 1.0 · June 2026
Governed by Czech law · Prague jurisdiction

Generated by ABOS IntraZone · Aviation Transparency Platform`;
}