import { atiBand } from "@/theme/atiPremium";

export const DIMS = [
  { key: "documentation",      label: "Documentation & Records" },
  { key: "technical",          label: "Technical Condition" },
  { key: "transparency",       label: "Seller Transparency" },
  { key: "transaction_ready",  label: "Transaction Readiness" },
  { key: "usage_mission",      label: "Usage & Mission" },
  { key: "storage_exposure",   label: "Storage & Exposure" },
  { key: "config_clarity",     label: "Configuration Clarity" },
  { key: "market_readiness",   label: "Market Readiness" },
];

export function genCode(reg, score) {
  // Fallback only — used if the backend deal_code couldn't be fetched (e.g. save_report failed).
  const chars = "ABCDEFGHJKLMNPQRSTUVWXYZ23456789";
  let suffix = "";
  for (let i = 0; i < 5; i++) suffix += chars[Math.floor(Math.random() * chars.length)];
  const r = (reg || "NREG").replace(/[^A-Z0-9]/gi, "").toUpperCase().slice(0, 6);
  return `ATI-${r}-${score}-${suffix}`;
}

// Builds the report code from the shared deal_code (same core ID as the Listing
// and ATI Score) so ATI-XXXXXX / SCORE-XXXXXX / LST-XXXXXX are trivially linkable.
export function buildReportCode(reg, score, dealCode) {
  const r = (reg || "NREG").replace(/[^A-Z0-9]/gi, "").toUpperCase().slice(0, 6);
  return `ATI-${r}-${score}-${dealCode}`;
}

// Generates a fresh 6-char shared core ID (same alphabet as the backend's
// getOrCreateDealCode in abosEntitlements) for a listing that doesn't have one yet.
export function generateDealCode() {
  const chars = "ABCDEFGHJKLMNPQRSTUVWXYZ23456789";
  let code = "";
  for (let i = 0; i < 6; i++) code += chars[Math.floor(Math.random() * chars.length)];
  return code;
}

export async function exportDocx(report, code) {
  const verdictFor = atiBand;
  const lines = [];
  lines.push("ATI REPORT powered by ABOS — Aircraft Buy Or Sell, since 2021");
  lines.push("=".repeat(64));
  lines.push(`Report Code: ${code}`);
  lines.push(`Generated: ${new Date().toLocaleDateString("en-GB", { day: "numeric", month: "long", year: "numeric" })}`);
  lines.push("");
  lines.push("AIRCRAFT IDENTITY");
  lines.push("-".repeat(40));
  (report.identity_rows || []).forEach(r => lines.push(`${r.label}: ${r.value}`));
  lines.push("");
  lines.push(`ATI TOTAL SCORE: ${report.total} / 120`);
  lines.push(`VERDICT: ${verdictFor(report.total).label}`);
  lines.push(`DEAL SCORE: ${((report.total / 120) * 10).toFixed(1)} / 10`);
  lines.push("");
  lines.push("DIMENSION SCORES");
  lines.push("-".repeat(40));
  DIMS.forEach(d => {
    const s = report[d.key] || 0;
    lines.push(`${d.label}: ${s}/15`);
    if (report.reasons?.[d.key]) lines.push(`  → ${report.reasons[d.key]}`);
  });
  lines.push("");
  lines.push("EXECUTIVE SUMMARY");
  lines.push("-".repeat(40));
  lines.push(report.summary || "");
  lines.push("");
  lines.push("KEY STRENGTHS");
  lines.push("-".repeat(40));
  (report.strengths || []).forEach(s => lines.push(`• ${s}`));
  lines.push("");
  lines.push("RISK FACTORS");
  lines.push("-".repeat(40));
  (report.risks || []).forEach(r => lines.push(`• ${r}`));
  lines.push("");
  lines.push("RECOMMENDATIONS");
  lines.push("-".repeat(40));
  (report.recommendations || []).forEach(r => lines.push(`• ${r}`));
  lines.push("");
  lines.push("─".repeat(64));
  lines.push("This report is generated by ABOS MarketSpace Aviation Intelligence.");
  lines.push("ABOS — Aircraft Buy Or Sell — since 2021.");

  const blob = new Blob([lines.join("\n")], { type: "application/vnd.openxmlformats-officedocument.wordprocessingml.document" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = `${code}.docx`;
  a.click();
  URL.revokeObjectURL(url);
}