// ABOS Product Catalog — current public pricing.
// Legacy products remain server-side for entitlement compatibility but are not marketed.
export const PRODUCT_CATALOG = [
  { key:'ATI_SCORE', name:'ATI Score', type:'one_time', price_eur:0, free:true, currency:'eur', category:'free', icon:'Shield', tagline:'Know the aircraft at a glance.', features:['ATI transparency score','Key risk signals','Data-quality indicators','Locked report preview'] },
  { key:'ATI_BASIC_REPORT', name:'ATI Report', type:'one_time', price_usd:49, currency:'usd', stripe_price_id:'price_1U7dkVAT7Be3WR6JsraFG9Ki', category:'buyer', icon:'FileBarChart', tagline:'Aircraft due diligence before you buy.', features:['Aircraft identity & provenance','Registry and verification signals','History and risk indicators','Data gaps and confidence','Sources and methodology','Report access per aircraft'] },
  { key:'ATI_PRO', name:'ATI Pro', type:'one_time', price_usd:199, currency:'usd', stripe_price_id:'price_1U7dkYAT7Be3WR6Jaf9jqrVV', category:'buyer', icon:'TrendingUp', tagline:'Financial Advisor + Investment Brief.', features:['Everything in ATI Report','Market valuation & comparables','CAPEX / OPEX analysis','Engine, MRO & avionics economics','Insurance estimate','Lease, financing & ownership scenarios','Investment Brief and decision analysis'] },
  { key:'ATI_PRO_TAX', name:'ATI Pro Tax', type:'one_time', price_usd:499, currency:'usd', stripe_price_id:'price_1U7dkbAT7Be3WR6JDOjfF3Eg', category:'buyer', icon:'Shield', tagline:'ATI Pro plus jurisdiction-specific tax & ownership analysis.', features:['Everything in ATI Pro','Tax jurisdiction analysis','Business-use scenarios','Ownership structure scenarios','Tax-adjusted economics','Insurance and compliance considerations','Professional review disclaimer'] },
  { key:'ATI_REPORT_PACK_5', name:'ATI Report — 5 Pack', type:'one_time', price_usd:199, currency:'usd', category:'volume', icon:'FileBarChart', report_credits:5, badge:null, tagline:'For buyers screening multiple aircraft.', features:['5 ATI Reports','Use across different aircraft','$39.80 per report','Credits do not expire while account is active'] },
  { key:'ATI_REPORT_PACK_10', name:'ATI Report — 10 Pack', type:'one_time', price_usd:290, currency:'usd', category:'volume', icon:'FileBarChart', report_credits:10, badge:'Best value', tagline:'For serious aircraft buyers and acquisition teams.', features:['10 ATI Reports','Use across different aircraft','$29 per report','Credits do not expire while account is active'] },
  { key:'ATI_REPORT_PACK_25', name:'ATI Report — 25 Pack', type:'one_time', price_usd:625, currency:'usd', category:'volume', icon:'FileBarChart', report_credits:25, badge:null, tagline:'For high-volume aircraft screening.', features:['25 ATI Reports','Use across different aircraft','$25 per report','Credits do not expire while account is active'] },
  { key:'ATI_FULL_REPORT', name:'ATI Full Report (legacy)', type:'one_time', price_eur:49, currency:'eur', legacy:true, category:'legacy', icon:'FileBarChart', tagline:'Legacy access for existing purchases.', features:['Existing entitlement compatibility'] },
  { key:'VALUATION_STUDIO', name:'Valuation Studio (legacy)', type:'one_time', price_eur:29, currency:'eur', legacy:true, category:'legacy', icon:'TrendingUp', tagline:'Legacy access only.', features:['Existing entitlement compatibility'] },
  { key:'VERIFICATION_PACK', name:'Verification Pack (legacy)', type:'one_time', price_eur:19.90, currency:'eur', legacy:true, category:'legacy', icon:'BadgeCheck', tagline:'Legacy access only.', features:['Existing entitlement compatibility'] },
  { key:'API_STARTER', name:'ABOS API — Starter', type:'subscription', price_eur:690, currency:'eur', interval:'month', category:'api', icon:'Crown', usage_label:'Included monthly report-equivalent usage (final allowance subject to API contract)', tagline:'Put ABOS aircraft intelligence into your product.', features:['Search','ATI Score','Tenant-scoped API key','Aircraft intelligence endpoints','Usage monitoring','API documentation'] },
  { key:'API_PROFESSIONAL', name:'ABOS API — Professional', type:'subscription', price_eur:1890, currency:'eur', interval:'month', category:'api', icon:'Building', usage_label:'Expanded monthly report-equivalent usage (final allowance subject to API contract)', tagline:'Aircraft reports, valuation and market intelligence at scale.', features:['Everything in Starter','ATI Report API','OMVM Valuation','Market Intelligence','Expanded usage','Developer integration support'] },
  { key:'API_ENTERPRISE', name:'ABOS API — Enterprise', type:'contract', price_eur:3900, currency:'eur', category:'api', icon:'Building', tagline:'Enterprise aircraft intelligence infrastructure.', features:['Full capability set','Aircraft Passport & registry intelligence','Advanced intelligence','Custom usage','Dedicated onboarding','Contracted support / SLA where agreed'] },
  { key:'WHITE_LABEL_LICENSE', name:'ABOS White-Label Integration License', type:'one_time', price_eur:2500, currency:'eur', category:'api', icon:'Crown', tagline:'One-time integration and lifetime license.', features:['Lifetime approved white-label license','Production integration setup','Tenant configuration','Integration documentation','Does not include unlimited API usage'] },
];
export const SUB_INCLUDED = {};
export const SUB_DISCOUNT = {};
export const ONE_TIME_PRODUCTS = PRODUCT_CATALOG.filter(p=>p.type==='one_time' && !p.legacy);
export const SUBSCRIPTION_PRODUCTS = PRODUCT_CATALOG.filter(p=>p.type==='subscription');
export const API_PRODUCTS = PRODUCT_CATALOG.filter(p=>p.category==='api');
export function getProduct(key){return PRODUCT_CATALOG.find(p=>p.key===key);}
export function formatEur(amount){return `€${Number(amount).toLocaleString('en-US',{minimumFractionDigits:0,maximumFractionDigits:2})}`;}
export function formatPrice(amount,currency='eur'){return `${currency==='usd'?'$':'€'}${Number(amount).toLocaleString('en-US',{minimumFractionDigits:0,maximumFractionDigits:2})}`;}
export function formatProductPrice(product){if(!product)return '';const amount=product.price_usd??product.price_eur;if(amount==null)return '';return formatPrice(amount,product.currency||'eur');}
export function effectivePrice(key){const p=getProduct(key);if(!p)return null;const amount=p.price_usd??p.price_eur;return {amount,currency:p.currency||'eur',included:false,original_amount:amount,discount_pct:0};}
