// Sales Pipeline Blueprint Templates
// Static "spider" definitions per aircraft class.
// Each step can be: AI-driven (auto-executable), manual, or document-review.

export const PIPELINE_TEMPLATES = {
  sep: [
    {
      id: "twin_init",
      label: "Digital Twin Initialization",
      description: "Aggregate FAA registry, engine specs, ADS-B traffic, and document trail into a unified Digital Twin.",
      category: "verification",
      ai_driven: true,
      function_name: "initDigitalTwin",
      prerequisite_ids: [],
    },
    {
      id: "ati_scoring",
      label: "ATI Transparency Scoring",
      description: "AI-driven 8-dimension scoring: documentation, technical condition, engine, avionics, history, storage, config, market readiness.",
      category: "valuation",
      ai_driven: true,
      function_name: "orchestrateATIScoring",
      prerequisite_ids: ["twin_init"],
    },
    {
      id: "market_valuation",
      label: "Expert Market Valuation",
      description: "Comparable-based market estimate with deal quality assessment and price band analysis.",
      category: "valuation",
      ai_driven: true,
      function_name: "marketExpertValuation",
      prerequisite_ids: ["ati_scoring"],
    },
    {
      id: "doc_upload",
      label: "Document Upload & OCR Intake",
      description: "Upload logbooks, airworthiness certificate, registration, weight & balance. AI extracts and indexes data fields.",
      category: "document",
      ai_driven: false,
      prerequisite_ids: ["twin_init"],
    },
    {
      id: "damage_history",
      label: "Damage History Verification",
      description: "AI cross-references FAA Form 337 filings, NTSB database, and seller disclosure for damage events and repairs.",
      category: "verification",
      ai_driven: true,
      prerequisite_ids: ["doc_upload"],
    },
    {
      id: "ad_sb_compliance",
      label: "AD / SB / STC Compliance Check",
      description: "Verify Airworthiness Directive and Service Bulletin compliance from maintenance records. Flag overdue or recurring ADs.",
      category: "verification",
      ai_driven: true,
      prerequisite_ids: ["doc_upload"],
    },
    {
      id: "logbook_review",
      label: "Maintenance Log & Logbook AI Review",
      description: "AI reviews logbook entries for completeness, consistency, hour-tracking accuracy, and red flags. Generates review report saved to vault.",
      category: "verification",
      ai_driven: true,
      prerequisite_ids: ["doc_upload"],
    },
    {
      id: "contract_draft",
      label: "Contract Template Generation",
      description: "AI generates filled purchase agreement / broker contract from Digital Twin + user profile data. Uses official FAA/EASA/CAA templates.",
      category: "legal",
      ai_driven: true,
      function_name: "executeBrokerAgreement",
      prerequisite_ids: ["market_valuation", "logbook_review"],
    },
    {
      id: "digital_signature",
      label: "Digital Signature Collection",
      description: "Route generated contract for e-signature with full audit trail. Resolves signature status from all parties.",
      category: "legal",
      ai_driven: false,
      prerequisite_ids: ["contract_draft"],
    },
    {
      id: "prebuy_inspection",
      label: "Pre-Buy Inspection (Certified A&P / IA)",
      description: "Schedule and complete pre-buy inspection by certified personnel. Expert network dispatch and report delivery.",
      category: "inspection",
      ai_driven: false,
      function_name: "expertCheckout",
      prerequisite_ids: ["digital_signature"],
    },
    {
      id: "escrow_setup",
      label: "Escrow & Payment Setup",
      description: "Initialize escrow deposit and payment flow via Stripe or USDC.",
      category: "financial",
      ai_driven: false,
      function_name: "stripeCreateCheckout",
      prerequisite_ids: ["prebuy_inspection"],
    },
    {
      id: "closing",
      label: "Closing & Title Transfer",
      description: "Final title transfer, registration change, bill of sale filing, and deal closure.",
      category: "closing",
      ai_driven: false,
      prerequisite_ids: ["escrow_setup"],
    },
  ],
  mep: [
    {
      id: "twin_init",
      label: "Digital Twin Initialization",
      description: "Aggregate registry, engine specs (multi-engine), ADS-B traffic, and document trail.",
      category: "verification",
      ai_driven: true,
      function_name: "initDigitalTwin",
      prerequisite_ids: [],
    },
    {
      id: "ati_scoring",
      label: "ATI Transparency Scoring",
      description: "8-dimension scoring with multi-engine risk assessment.",
      category: "valuation",
      ai_driven: true,
      function_name: "orchestrateATIScoring",
      prerequisite_ids: ["twin_init"],
    },
    {
      id: "market_valuation",
      label: "Expert Market Valuation",
      description: "Comparable-based market estimate for twin-engine piston.",
      category: "valuation",
      ai_driven: true,
      function_name: "marketExpertValuation",
      prerequisite_ids: ["ati_scoring"],
    },
    {
      id: "doc_upload",
      label: "Document Upload & OCR Intake",
      description: "Upload logbooks (both engines), airworthiness, registration, W&B.",
      category: "document",
      ai_driven: false,
      prerequisite_ids: ["twin_init"],
    },
    {
      id: "damage_history",
      label: "Damage History Verification",
      description: "AI cross-references Form 337, NTSB, and seller disclosure.",
      category: "verification",
      ai_driven: true,
      prerequisite_ids: ["doc_upload"],
    },
    {
      id: "ad_sb_compliance",
      label: "AD / SB / STC Compliance Check",
      description: "Verify AD/SB compliance for both engines and airframe.",
      category: "verification",
      ai_driven: true,
      prerequisite_ids: ["doc_upload"],
    },
    {
      id: "logbook_review",
      label: "Maintenance Log & Logbook AI Review",
      description: "AI reviews logbook entries for both engines. Generates review report.",
      category: "verification",
      ai_driven: true,
      prerequisite_ids: ["doc_upload"],
    },
    {
      id: "contract_draft",
      label: "Contract Template Generation",
      description: "AI generates filled purchase agreement from Digital Twin data.",
      category: "legal",
      ai_driven: true,
      function_name: "executeBrokerAgreement",
      prerequisite_ids: ["market_valuation", "logbook_review"],
    },
    {
      id: "digital_signature",
      label: "Digital Signature Collection",
      description: "Route contract for e-signature with audit trail.",
      category: "legal",
      ai_driven: false,
      prerequisite_ids: ["contract_draft"],
    },
    {
      id: "prebuy_inspection",
      label: "Pre-Buy Inspection (Certified A&P / IA)",
      description: "Schedule and complete pre-buy inspection. Twin-engine specialist preferred.",
      category: "inspection",
      ai_driven: false,
      function_name: "expertCheckout",
      prerequisite_ids: ["digital_signature"],
    },
    {
      id: "escrow_setup",
      label: "Escrow & Payment Setup",
      description: "Initialize escrow deposit and payment flow.",
      category: "financial",
      ai_driven: false,
      function_name: "stripeCreateCheckout",
      prerequisite_ids: ["prebuy_inspection"],
    },
    {
      id: "closing",
      label: "Closing & Title Transfer",
      description: "Final title transfer, registration change, deal closure.",
      category: "closing",
      ai_driven: false,
      prerequisite_ids: ["escrow_setup"],
    },
  ],
  turboprop: [
    {
      id: "twin_init",
      label: "Digital Twin Initialization",
      description: "Aggregate registry, turbine engine specs, ADS-B traffic, document trail.",
      category: "verification",
      ai_driven: true,
      function_name: "initDigitalTwin",
      prerequisite_ids: [],
    },
    {
      id: "ati_scoring",
      label: "ATI Transparency Scoring",
      description: "8-dimension scoring with turbine-specific risk assessment (TBO cycles, hot section).",
      category: "valuation",
      ai_driven: true,
      function_name: "orchestrateATIScoring",
      prerequisite_ids: ["twin_init"],
    },
    {
      id: "market_valuation",
      label: "Expert Market Valuation",
      description: "Comparable-based market estimate for turboprop class.",
      category: "valuation",
      ai_driven: true,
      function_name: "marketExpertValuation",
      prerequisite_ids: ["ati_scoring"],
    },
    {
      id: "doc_upload",
      label: "Document Upload & OCR Intake",
      description: "Upload logbooks, hot section inspection reports, airworthiness, registration.",
      category: "document",
      ai_driven: false,
      prerequisite_ids: ["twin_init"],
    },
    {
      id: "damage_history",
      label: "Damage History Verification",
      description: "AI cross-references Form 337, NTSB, and seller disclosure.",
      category: "verification",
      ai_driven: true,
      prerequisite_ids: ["doc_upload"],
    },
    {
      id: "ad_sb_compliance",
      label: "AD / SB / STC Compliance Check",
      description: "Verify AD/SB compliance including hot section inspection intervals.",
      category: "verification",
      ai_driven: true,
      prerequisite_ids: ["doc_upload"],
    },
    {
      id: "logbook_review",
      label: "Maintenance Log & Logbook AI Review",
      description: "AI reviews logbook entries with turbine-specific checks. Generates review report.",
      category: "verification",
      ai_driven: true,
      prerequisite_ids: ["doc_upload"],
    },
    {
      id: "contract_draft",
      label: "Contract Template Generation",
      description: "AI generates filled purchase agreement from Digital Twin data.",
      category: "legal",
      ai_driven: true,
      function_name: "executeBrokerAgreement",
      prerequisite_ids: ["market_valuation", "logbook_review"],
    },
    {
      id: "digital_signature",
      label: "Digital Signature Collection",
      description: "Route contract for e-signature with audit trail.",
      category: "legal",
      ai_driven: false,
      prerequisite_ids: ["contract_draft"],
    },
    {
      id: "prebuy_inspection",
      label: "Pre-Buy Inspection (Certified — Turbine Rated)",
      description: "Schedule and complete pre-buy inspection by turbine-rated IA.",
      category: "inspection",
      ai_driven: false,
      function_name: "expertCheckout",
      prerequisite_ids: ["digital_signature"],
    },
    {
      id: "escrow_setup",
      label: "Escrow & Payment Setup",
      description: "Initialize escrow deposit and payment flow.",
      category: "financial",
      ai_driven: false,
      function_name: "stripeCreateCheckout",
      prerequisite_ids: ["prebuy_inspection"],
    },
    {
      id: "closing",
      label: "Closing & Title Transfer",
      description: "Final title transfer, registration change, deal closure.",
      category: "closing",
      ai_driven: false,
      prerequisite_ids: ["escrow_setup"],
    },
  ],
  jet: [
    {
      id: "twin_init",
      label: "Digital Twin Initialization",
      description: "Aggregate registry, turbofan engine specs, ADS-B traffic, document trail.",
      category: "verification",
      ai_driven: true,
      function_name: "initDigitalTwin",
      prerequisite_ids: [],
    },
    {
      id: "ati_scoring",
      label: "ATI Transparency Scoring",
      description: "8-dimension scoring with jet-specific risk assessment (cycles, TBO, RVSM).",
      category: "valuation",
      ai_driven: true,
      function_name: "orchestrateATIScoring",
      prerequisite_ids: ["twin_init"],
    },
    {
      id: "market_valuation",
      label: "Expert Market Valuation",
      description: "Comparable-based market estimate for jet class.",
      category: "valuation",
      ai_driven: true,
      function_name: "marketExpertValuation",
      prerequisite_ids: ["ati_scoring"],
    },
    {
      id: "doc_upload",
      label: "Document Upload & OCR Intake",
      description: "Upload logbooks, engine trend monitoring data, RVSM reports, airworthiness, registration.",
      category: "document",
      ai_driven: false,
      prerequisite_ids: ["twin_init"],
    },
    {
      id: "damage_history",
      label: "Damage History Verification",
      description: "AI cross-references Form 337, NTSB, and seller disclosure.",
      category: "verification",
      ai_driven: true,
      prerequisite_ids: ["doc_upload"],
    },
    {
      id: "ad_sb_compliance",
      label: "AD / SB / STC Compliance Check",
      description: "Verify AD/SB compliance including engine trend monitoring and RVSM certification.",
      category: "verification",
      ai_driven: true,
      prerequisite_ids: ["doc_upload"],
    },
    {
      id: "logbook_review",
      label: "Maintenance Log & Logbook AI Review",
      description: "AI reviews logbook entries with jet-specific checks. Generates review report.",
      category: "verification",
      ai_driven: true,
      prerequisite_ids: ["doc_upload"],
    },
    {
      id: "contract_draft",
      label: "Contract Template Generation",
      description: "AI generates filled purchase agreement from Digital Twin data.",
      category: "legal",
      ai_driven: true,
      function_name: "executeBrokerAgreement",
      prerequisite_ids: ["market_valuation", "logbook_review"],
    },
    {
      id: "digital_signature",
      label: "Digital Signature Collection",
      description: "Route contract for e-signature with audit trail.",
      category: "legal",
      ai_driven: false,
      prerequisite_ids: ["contract_draft"],
    },
    {
      id: "prebuy_inspection",
      label: "Pre-Buy Inspection (Certified — Jet Type Rated)",
      description: "Schedule and complete pre-buy inspection by type-rated IA.",
      category: "inspection",
      ai_driven: false,
      function_name: "expertCheckout",
      prerequisite_ids: ["digital_signature"],
    },
    {
      id: "escrow_setup",
      label: "Escrow & Payment Setup",
      description: "Initialize escrow deposit and payment flow.",
      category: "financial",
      ai_driven: false,
      function_name: "stripeCreateCheckout",
      prerequisite_ids: ["prebuy_inspection"],
    },
    {
      id: "closing",
      label: "Closing & Title Transfer",
      description: "Final title transfer, registration change, deal closure.",
      category: "closing",
      ai_driven: false,
      prerequisite_ids: ["escrow_setup"],
    },
  ],
  helicopter: [
    {
      id: "twin_init",
      label: "Digital Twin Initialization",
      description: "Aggregate registry, engine specs, ADS-B traffic, document trail.",
      category: "verification",
      ai_driven: true,
      function_name: "initDigitalTwin",
      prerequisite_ids: [],
    },
    {
      id: "ati_scoring",
      label: "ATI Transparency Scoring",
      description: "8-dimension scoring with rotorcraft-specific risk assessment.",
      category: "valuation",
      ai_driven: true,
      function_name: "orchestrateATIScoring",
      prerequisite_ids: ["twin_init"],
    },
    {
      id: "market_valuation",
      label: "Expert Market Valuation",
      description: "Comparable-based market estimate for rotorcraft.",
      category: "valuation",
      ai_driven: true,
      function_name: "marketExpertValuation",
      prerequisite_ids: ["ati_scoring"],
    },
    {
      id: "doc_upload",
      label: "Document Upload & OCR Intake",
      description: "Upload logbooks, rotor track & balance reports, airworthiness, registration.",
      category: "document",
      ai_driven: false,
      prerequisite_ids: ["twin_init"],
    },
    {
      id: "damage_history",
      label: "Damage History Verification",
      description: "AI cross-references Form 337, NTSB, and seller disclosure.",
      category: "verification",
      ai_driven: true,
      prerequisite_ids: ["doc_upload"],
    },
    {
      id: "ad_sb_compliance",
      label: "AD / SB / STC Compliance Check",
      description: "Verify AD/SB compliance including rotor and dynamic component limits.",
      category: "verification",
      ai_driven: true,
      prerequisite_ids: ["doc_upload"],
    },
    {
      id: "logbook_review",
      label: "Maintenance Log & Logbook AI Review",
      description: "AI reviews logbook entries with rotorcraft-specific checks. Generates review report.",
      category: "verification",
      ai_driven: true,
      prerequisite_ids: ["doc_upload"],
    },
    {
      id: "contract_draft",
      label: "Contract Template Generation",
      description: "AI generates filled purchase agreement from Digital Twin data.",
      category: "legal",
      ai_driven: true,
      function_name: "executeBrokerAgreement",
      prerequisite_ids: ["market_valuation", "logbook_review"],
    },
    {
      id: "digital_signature",
      label: "Digital Signature Collection",
      description: "Route contract for e-signature with audit trail.",
      category: "legal",
      ai_driven: false,
      prerequisite_ids: ["contract_draft"],
    },
    {
      id: "prebuy_inspection",
      label: "Pre-Buy Inspection (Certified — Rotorcraft)",
      description: "Schedule and complete pre-buy inspection by rotorcraft-rated IA.",
      category: "inspection",
      ai_driven: false,
      function_name: "expertCheckout",
      prerequisite_ids: ["digital_signature"],
    },
    {
      id: "escrow_setup",
      label: "Escrow & Payment Setup",
      description: "Initialize escrow deposit and payment flow.",
      category: "financial",
      ai_driven: false,
      function_name: "stripeCreateCheckout",
      prerequisite_ids: ["prebuy_inspection"],
    },
    {
      id: "closing",
      label: "Closing & Title Transfer",
      description: "Final title transfer, registration change, deal closure.",
      category: "closing",
      ai_driven: false,
      prerequisite_ids: ["escrow_setup"],
    },
  ],
};

export const CATEGORY_META = {
  verification: { label: "Verification", color: "#4e8ef7", icon: "ShieldCheck" },
  document: { label: "Documents", color: "#a78bfa", icon: "FileText" },
  valuation: { label: "Valuation", color: "#f5c242", icon: "TrendingUp" },
  financial: { label: "Financial", color: "#5dcaa5", icon: "DollarSign" },
  inspection: { label: "Inspection", color: "#e8a83a", icon: "CheckCircle" },
  legal: { label: "Legal", color: "#c084fc", icon: "Scale" },
  closing: { label: "Closing", color: "#0f7a56", icon: "Flag" },
};

export function detectAircraftClass(make, model, engineType) {
  const m = `${make} ${model}`.toLowerCase();
  if (/king air|pc-12|tbm|questool|caravan|pc6/.test(m)) return "turboprop";
  if (/citation|phenom|mustang|vision|cirrus vision|embraer|lear|gulfstream|challenger/.test(m)) return "jet";
  if (/robinson|bell|airbus helicopter|ec130|ec135|as350|r44|r66|b206|h125/.test(m)) return "helicopter";
  if (/baron|duchess|seminole|travel air|twinstar|da42|piper seneca/.test(m)) return "mep";
  return "sep";
}

export function getTemplate(aircraftClass) {
  return PIPELINE_TEMPLATES[aircraftClass] || PIPELINE_TEMPLATES.sep;
}