import { useState } from "react";
import { ArrowRight, X } from "lucide-react";
import { Link } from "react-router-dom";

export default function BuySellHero() {
  const [hoveredWord, setHoveredWord] = useState("");
  const [showModal, setShowModal] = useState(false);
  const active = hoveredWord === "or";
  const wordClass = (word) => `inline-block cursor-pointer rounded-lg px-2 transition-[opacity,transform,color,background-color] duration-200 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-primary ${active || hoveredWord === word ? "opacity-100 text-foreground" : "opacity-65"}`;
  return <section className="min-h-[calc(100vh-72px)] bg-background px-5 py-10 md:px-10"><div className="mx-auto flex min-h-[calc(100vh-152px)] max-w-6xl flex-col justify-center"><p className="mb-5 font-mono text-xs font-bold uppercase tracking-[0.22em] text-muted-foreground">ABOS · Transaction Intelligence</p><h1 className="max-w-5xl text-balance text-6xl font-black leading-[.92] tracking-[-0.06em] text-foreground sm:text-7xl md:text-9xl"><Link to="/buy" className={wordClass("buy")} onMouseEnter={() => setHoveredWord("buy")} onMouseLeave={() => setHoveredWord("")}>Aircraft BUY</Link><button type="button" aria-label="Choose buyer or seller role" className={`mx-1 inline-block cursor-pointer rounded-lg px-2 font-inherit text-gold transition-[transform,color,text-shadow] duration-200 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-primary ${active ? "scale-105 text-gold-bright" : ""}`} style={active ? { textShadow: "0 0 28px rgba(245,200,66,.65)" } : {}} onMouseEnter={() => setHoveredWord("or")} onMouseLeave={() => setHoveredWord("")} onClick={() => setShowModal(true)}>or</button><Link to="/sell" className={wordClass("sell")} onMouseEnter={() => setHoveredWord("sell")} onMouseLeave={() => setHoveredWord("")}>SELL</Link></h1><p className="mt-8 max-w-2xl text-pretty text-lg leading-8 text-muted-foreground">Make every aircraft decision with market intelligence, verified data and a structured route to close.</p><div className="mt-10 flex flex-wrap gap-3"><Link className="rounded-xl bg-accent px-5 py-3 font-semibold text-accent-foreground transition-opacity hover:opacity-90" to="/buy">Explore BUY intelligence <ArrowRight className="ml-1 inline h-4 w-4" /></Link><Link className="rounded-xl bg-primary px-5 py-3 font-semibold text-primary-foreground transition-opacity hover:opacity-90" to="/sell">Prepare a SELL asset <ArrowRight className="ml-1 inline h-4 w-4" /></Link></div></div>{showModal && <div className="fixed inset-0 z-30 grid place-items-center bg-foreground/30 p-5" role="dialog" aria-modal="true" aria-labelledby="role-choice-title"><div className="w-full max-w-md rounded-2xl border border-border bg-card p-6 shadow-xl"><button type="button" className="float-right rounded-md p-2 text-muted-foreground hover:bg-muted" aria-label="Close role selector" onClick={() => setShowModal(false)}><X className="h-5 w-5" /></button><p className="font-mono text-xs uppercase tracking-widest text-gold">The $ connector</p><h2 id="role-choice-title" className="mt-3 text-2xl font-bold">ABOS propojuje kupující a prodejce.</h2><p className="mt-3 text-muted-foreground">Vyber svou roli. Můžeš aktivovat obě pipeline.</p><div className="mt-6 grid grid-cols-2 gap-3"><Link to="/buy" className="rounded-xl bg-accent px-4 py-3 text-center font-semibold text-accent-foreground">BUY</Link><Link to="/sell" className="rounded-xl bg-primary px-4 py-3 text-center font-semibold text-primary-foreground">SELL</Link></div></div></div>}</section>;
}