import { useMemo, useState } from "react";
import { Link } from "react-router-dom";
import { useQuery } from "@tanstack/react-query";
import { base44 } from "@/api/base44Client";
import RotatingGlobe from "@/components/dashboard/RotatingGlobe";
import PipelineNodeCanvas from "@/components/pipeline/PipelineNodeCanvas";
import { FileText, Landmark, ShieldCheck, Target, TrendingUp } from "lucide-react";

const cardStyle = { background: "rgba(255,255,255,0.035)", border: "1px solid rgba(255,255,255,0.10)" };
const steps = ["Identify", "Verify", "Structure", "Close"];

function Signal({ label, value, emptyMessage, Icon }) {
  return <div className="rounded-xl p-4" style={cardStyle}><div className="flex items-center gap-2 text-white/45"><Icon className="h-4 w-4 text-[#D4A017]" /><span className="text-[10px] font-bold uppercase tracking-wider">{label}</span></div><p className="mt-2 text-2xl font-black text-white">{value}</p>{value === 0 && <p className="mt-1 text-xs text-white/45">{emptyMessage}</p>}</div>;
}

export default function IntraZoneOverview() {
  const [selectedId, setSelectedId] = useState("");
  const { data: listings = [] } = useQuery({ queryKey: ["intrazone-listings"], queryFn: () => base44.entities.AircraftListing.filter({ status: "active" }, "-ati_score", 100) });
  const { data: leads = [] } = useQuery({ queryKey: ["intrazone-leads"], queryFn: () => base44.entities.Lead.list("-created_date", 200) });
  const { data: escrows = [] } = useQuery({ queryKey: ["intrazone-escrows"], queryFn: () => base44.entities.EscrowTransaction.list("-created_date", 200) });
  const { data: passports = [] } = useQuery({ queryKey: ["intrazone-passports"], queryFn: () => base44.entities.ATIPassport.list("-updated_date", 200) });
  const { data: pipelines = [] } = useQuery({ queryKey: ["intrazone-pipelines"], queryFn: () => base44.entities.SalesPipeline.list("-updated_date", 100) });
  const selected = listings.find((listing) => listing.id === selectedId);
  const passport = passports.find((item) => item.listing === selected?.id || item.registration === selected?.registration);
  const pipeline = pipelines.find((item) => item.listing_id === selected?.id || item.registration === selected?.registration);
  const linkedLeads = useMemo(() => selected ? leads.filter((lead) => lead.listing === selected.id).length : 0, [leads, selected]);

  return <div className="space-y-5">
    <section><p className="text-[10px] font-bold uppercase tracking-[0.18em] text-[#D4A017]">Overview</p><h2 className="mt-1 text-2xl font-black">Global Signals</h2><div className="mt-4 grid grid-cols-2 gap-3 lg:grid-cols-4"><Signal label="Active aircraft" value={listings.length} emptyMessage="No active aircraft in your workspace" Icon={Target} /><Signal label="Active leads" value={leads.filter((lead) => !["closed", "lost"].includes(lead.status)).length} emptyMessage="No leads yet" Icon={TrendingUp} /><Signal label="ATI passports" value={passports.length} emptyMessage="No ATI passports yet" Icon={ShieldCheck} /><Signal label="Escrow records" value={escrows.length} emptyMessage="No escrow records yet" Icon={Landmark} /></div></section>
    <section className="grid gap-5 xl:grid-cols-[1.35fr_0.65fr]"><div className="min-h-[360px] rounded-2xl overflow-hidden" style={cardStyle}><div className="flex items-center justify-between border-b border-white/10 px-5 py-4"><div><p className="text-sm font-black">Aircraft Intelligence Map</p><p className="text-xs text-white/45">Active aircraft from the current ABOS inventory</p></div><span className="text-xs font-bold text-[#D4A017]">{listings.length} active</span></div><div className="h-[300px]"><RotatingGlobe theme="dark" listings={listings} showFallbackMarkers={false} /></div></div>
      <div className="rounded-2xl p-5" style={cardStyle}><p className="text-[10px] font-bold uppercase tracking-[0.18em] text-[#D4A017]">Active aircraft context</p><select value={selectedId} onChange={(event) => setSelectedId(event.target.value)} className="mt-4 w-full rounded-xl border border-white/15 bg-[#10131b] px-3 py-2.5 text-sm text-white"><option value="">Select an aircraft</option>{listings.map((listing) => <option key={listing.id} value={listing.id}>{listing.registration || "No registration"} · {listing.year || ""} {listing.make} {listing.model}</option>)}</select>{selected ? <div className="mt-5 space-y-3"><p className="text-lg font-black">{selected.year || ""} {selected.make} {selected.model}</p><p className="font-mono text-sm text-[#D4A017]">{selected.registration || "No registration"}</p><Link to={`/ati-passport/${selected.id}`} className="inline-flex text-sm font-bold text-[#D4A017] hover:underline">Open ATI Passport →</Link></div> : <p className="mt-5 text-sm text-white/45">{listings.length ? "No aircraft selected" : "No active aircraft in your workspace"}</p>}</div>
    </section>
    <section className="rounded-2xl p-5" style={cardStyle}><div className="flex items-center justify-between gap-4"><div><p className="text-[10px] font-bold uppercase tracking-[0.18em] text-[#D4A017]">ATI Card orchestration</p><p className="mt-1 text-sm text-white/50">ATI Score, valuation, documents, matching, negotiation, and escrow status.</p></div><span className="text-xs font-bold text-white/45">{pipeline ? "Workflow active" : "No workflow active"}</span></div>{selected && pipeline ? <div className="mt-5"><PipelineNodeCanvas pipeline={pipeline} passport={passport} /></div> : <p className="mt-5 rounded-xl border border-dashed border-white/15 p-7 text-center text-sm text-white/45">{selected ? "No workflow exists for this aircraft" : "No aircraft selected"}</p>}</section>
    <section className="grid gap-3 md:grid-cols-4">{steps.map((step, index) => <div key={step} className="rounded-xl p-4" style={cardStyle}><p className="text-[10px] font-bold uppercase tracking-wider text-white/40">0{index + 1}</p><p className="mt-1 font-black">{step}</p><p className="mt-1 text-xs text-white/45">{pipeline?.steps?.find((item) => item.label?.toLowerCase().includes(step.toLowerCase()))?.status || "Not started"}</p></div>)}</section>
    <section className="rounded-2xl p-5" style={cardStyle}><p className="text-[10px] font-bold uppercase tracking-[0.18em] text-[#D4A017]">Integrations</p><div className="mt-4 flex flex-wrap gap-2">{["Gmail", "Google Docs", "Google Calendar", "Supabase"].map((name) => <span key={name} className="rounded-full border border-white/10 bg-white/5 px-3 py-2 text-xs font-bold text-white/65">{name}</span>)}</div><div className="mt-5 grid gap-3 sm:grid-cols-3"><Link to="/bill-of-sale" className="rounded-xl border border-white/10 bg-white/5 p-3 text-sm font-bold text-white hover:border-[#D4A017]/50"><FileText className="mb-2 h-4 w-4 text-[#D4A017]" />Documents</Link><Link to="/escrow" className="rounded-xl border border-white/10 bg-white/5 p-3 text-sm font-bold text-white hover:border-[#D4A017]/50"><Landmark className="mb-2 h-4 w-4 text-[#D4A017]" />Escrow Status</Link><Link to="/integration-kit" className="rounded-xl border border-white/10 bg-white/5 p-3 text-sm font-bold text-white hover:border-[#D4A017]/50"><Target className="mb-2 h-4 w-4 text-[#D4A017]" />Integration Kit</Link></div></section>
  </div>;
}