/**
 * OMVM 2.0 Market Model
 * Stateless normalization, weighting and robust aggregation of live ASKING prices.
 */
export type MarketSource = 'controller' | 'trade_a_plane' | 'barnstormers' | 'aso' | 'other';
export interface MarketListing { source: MarketSource; listing_id: string; price_usd: number; observed_at?: string; make?: string; model?: string; year?: number; hours?: number; tbo_remaining_pct?: number; avionics_score?: number; feature_completeness?: number; dealer_id?: string; }
export interface ListingWeight { source_reliability: number; freshness: number; identity_match: number; feature_completeness: number; independence: number; final_weight: number; }
export interface MarketModelResult { observation_count: number; effective_sample_size: number; market_value_usd: number; market_sigma_usd: number; market_sigma_log: number; weighted_observations: Array<{ listing: MarketListing; weight: ListingWeight; log_price: number }>; model_mode: 'full_hedonic' | 'reduced_hedonic' | 'robust_median' | 'fallback'; deduplication_notes: string[]; }
const SOURCE_WEIGHTS: Record<MarketSource, number> = { controller: 1, trade_a_plane: .95, aso: .9, barnstormers: .8, other: .7 };
function freshness(s?: string): number { if (!s) return .7; const t=Date.parse(s); if(!Number.isFinite(t))return .65; const d=Math.max(0,(Date.now()-t)/86400000); if(d<=7)return 1; if(d<=30)return 1-((d-7)/23)*.1; if(d<=90)return .9-((d-30)/60)*.4; return Math.max(.3,.5-((d-90)/100)*.2); }
function identity(l:MarketListing,make:string,model:string):number { if(!l.make&&!l.model)return .7; const a=(l.make||'').trim().toLowerCase(),b=(l.model||'').trim().toLowerCase(),c=make.trim().toLowerCase(),d=model.trim().toLowerCase(); if(a===c&&b===d)return 1; if(a===c)return .8; return .5; }
function completeness(l:MarketListing):number { if(l.feature_completeness!==undefined)return Math.max(0,Math.min(1,l.feature_completeness)); let s=.5; if(l.year!==undefined)s+=.15; if(l.hours!==undefined)s+=.15; if(l.tbo_remaining_pct!==undefined)s+=.1; if(l.avionics_score!==undefined)s+=.1; return Math.min(1,s); }
function sameObservation(a:MarketListing,b:MarketListing):boolean { if(a.source===b.source&&a.listing_id&&a.listing_id===b.listing_id)return true; if(a.price_usd!==b.price_usd)return false; const same=(a.make||'').toLowerCase()===(b.make||'').toLowerCase()&&(a.model||'').toLowerCase()===(b.model||'').toLowerCase(); const hoursClose=a.hours===undefined||b.hours===undefined||Math.abs(a.hours-b.hours)<=25; return same&&hoursClose; }
function independence(a:MarketListing,b:MarketListing):number { if(sameObservation(a,b))return .15; if(a.dealer_id&&b.dealer_id&&a.dealer_id===b.dealer_id)return .45; const ta=Date.parse(a.observed_at||''),tb=Date.parse(b.observed_at||''); const close=Number.isFinite(ta)&&Number.isFinite(tb)&&Math.abs(ta-tb)<14*86400000; return a.source===b.source&&close ? .7 : 1; }
function weightedMedian(v:Array<{value:number;weight:number}>):number { const x=[...v].sort((a,b)=>a.value-b.value),total=x.reduce((s,q)=>s+q.weight,0);let acc=0;for(const q of x){acc+=q.weight;if(acc>=total/2)return q.value;}return x[x.length-1]?.value??NaN; }
export function calculateMarketValue(listings:MarketListing[],subject_make:string,subject_model:string):MarketModelResult {
 const notes:string[]=[]; if(!listings?.length)return {observation_count:0,effective_sample_size:0,market_value_usd:NaN,market_sigma_usd:NaN,market_sigma_log:NaN,weighted_observations:[],model_mode:'fallback',deduplication_notes:['No listings provided']};
 const seen=new Set<string>(),valid:MarketListing[]=[]; for(const l of listings){if(!(l.price_usd>5000)||l.price_usd>100000000||!Number.isFinite(l.price_usd)){notes.push(`Filtered ${l.source}/${l.listing_id}: invalid asking price`);continue;}const key=`${l.source}|${l.listing_id}|${l.price_usd}|${l.make||''}|${l.model||''}|${l.hours??''}`.toLowerCase();if(seen.has(key)){notes.push(`Duplicate removed: ${l.source}/${l.listing_id}`);continue;}seen.add(key);valid.push(l);}
 const weighted=valid.map((listing,idx)=>{const source_reliability=SOURCE_WEIGHTS[listing.source]??.7,f=freshness(listing.observed_at),im=identity(listing,subject_make,subject_model),fc=completeness(listing),ind=idx?Math.min(...valid.slice(0,idx).map(p=>independence(listing,p))):1,w=source_reliability*f*im*fc*ind;return {listing,weight:{source_reliability,freshness:f,identity_match:im,feature_completeness:fc,independence:ind,final_weight:w},log_price:Math.log(listing.price_usd)};});
 const sumW=weighted.reduce((s,x)=>s+x.weight.final_weight,0),sumW2=weighted.reduce((s,x)=>s+x.weight.final_weight**2,0),nEff=sumW2?(sumW**2)/sumW2:0;
 if(nEff<2)return {observation_count:valid.length,effective_sample_size:nEff,market_value_usd:NaN,market_sigma_usd:NaN,market_sigma_log:NaN,weighted_observations:weighted,model_mode:'fallback',deduplication_notes:[...notes,`Insufficient effective observations: ${nEff.toFixed(2)}`]};
 const med=weightedMedian(weighted.map(x=>({value:x.log_price,weight:x.weight.final_weight}))); const mad=weightedMedian(weighted.map(x=>({value:Math.abs(x.log_price-med),weight:x.weight.final_weight}))); const scale=Math.max(.035,1.4826*mad); const clipped=weighted.map(x=>({...x,rw:x.weight.final_weight*Math.min(1,scale/Math.max(scale,Math.abs(x.log_price-med)))})); const rs=clipped.reduce((s,x)=>s+x.rw,0),mu=clipped.reduce((s,x)=>s+x.rw*x.log_price,0)/rs,variance=Math.max(0,clipped.reduce((s,x)=>s+x.rw*(x.log_price-mu)**2,0)/rs),sigma=Math.max(.035,Math.sqrt(variance)),value=Math.exp(mu+.5*sigma**2),mode=nEff>=8?'full_hedonic':nEff>=5?'reduced_hedonic':'robust_median'; if(nEff<5)notes.push('Thin market: robust aggregation used; no regression claim.');
 return {observation_count:valid.length,effective_sample_size:nEff,market_value_usd:value,market_sigma_usd:value*Math.sqrt(Math.exp(sigma**2)-1),market_sigma_log:sigma,weighted_observations:weighted,model_mode:mode,deduplication_notes:notes};
}
