import jsPDF from "jspdf";

export async function exportVerifyReportPDF({ session, documents = [], score }) {
  const doc = new jsPDF({ orientation: "portrait", unit: "mm", format: "a4" });
  const W = 210;
  const margin = 14;
  const contentW = W - margin * 2;
  let y = 0;

  // Header band
  doc.setFillColor(11, 19, 36);
  doc.rect(0, 0, W, 36, "F");

  doc.setTextColor(96, 165, 250);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(9);
  doc.text("ATI VERIFY · REMOTE VERIFICATION", margin, 10);

  doc.setTextColor(255, 255, 255);
  doc.setFontSize(17);
  doc.text("Verification Report", margin, 21);

  doc.setFontSize(7);
  doc.setTextColor(148, 163, 184);
  doc.text(`Generated: ${new Date().toLocaleDateString("en-GB", { day: "2-digit", month: "short", year: "numeric" })}`, W - margin, 10, { align: "right" });

  y = 44;

  // Session ID block
  doc.setFillColor(17, 22, 43);
  doc.roundedRect(margin, y, contentW, 16, 2, 2, "F");
  doc.setFont("helvetica", "bold");
  doc.setFontSize(11);
  doc.setTextColor(96, 165, 250);
  doc.text(session.session_code, margin + 5, y + 8);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(7);
  doc.setTextColor(148, 163, 184);
  const vfyLabel = session.verification_status ? session.verification_status.replace("_", " ").toUpperCase() : "PENDING";
  const vfyColor = session.verification_status === "verified" ? [74, 222, 128] : session.verification_status === "review_required" ? [250, 204, 21] : [248, 113, 113];
  doc.setTextColor(...vfyColor);
  doc.text(vfyLabel, W - margin - 5, y + 8, { align: "right" });

  y += 23;

  // Party details
  doc.setFont("helvetica", "bold");
  doc.setFontSize(8);
  doc.setTextColor(148, 163, 184);
  doc.text("PARTIES INVOLVED", margin, y);
  y += 5;

  const parties = [
    ["Broker / Inspector", session.broker_name || "—"],
    ["Seller / Owner", session.seller_name || "—"],
    ["Aircraft Registration", session.aircraft_registration || "—"],
    ["Aircraft Type", session.aircraft_type || "—"],
    ["Serial Number (MSN)", session.aircraft_serial || "—"],
  ];
  parties.forEach(([k, v]) => {
    doc.setFont("helvetica", "normal");
    doc.setFontSize(7);
    doc.setTextColor(100, 116, 139);
    doc.text(k, margin + 2, y);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(220, 225, 235);
    doc.text(v, margin + 60, y);
    y += 5;
  });

  y += 5;

  // ATI Scores
  if (score) {
    doc.setFont("helvetica", "bold");
    doc.setFontSize(8);
    doc.setTextColor(248, 250, 252);
    doc.text("ATI VERIFICATION SCORES", margin, y);
    y += 7;

    const scoreItems = [
      ["ATI Identity Score", score.identity_score, [74, 222, 128]],
      ["ATI Ownership Score", score.ownership_score, [96, 165, 250]],
      ["ATI Document Confidence", score.document_confidence_score, [250, 204, 21]],
      ["ATI Overall Score", score.overall_score, [192, 132, 252]],
    ];

    scoreItems.forEach(([label, val, color]) => {
      const pct = val != null ? val / 100 : 0;
      doc.setFont("helvetica", "normal");
      doc.setFontSize(7);
      doc.setTextColor(148, 163, 184);
      doc.text(label, margin + 2, y);

      // Bar
      doc.setFillColor(30, 35, 55);
      doc.roundedRect(margin + 70, y - 3, contentW - 90, 3.5, 0.5, 0.5, "F");
      doc.setFillColor(...color);
      doc.roundedRect(margin + 70, y - 3, (contentW - 90) * pct, 3.5, 0.5, 0.5, "F");

      doc.setFont("helvetica", "bold");
      doc.setTextColor(...color);
      doc.text(val != null ? String(val) : "—", W - margin - 2, y, { align: "right" });
      y += 6;
    });

    y += 5;
  }

  // Documents
  if (documents.length > 0) {
    doc.setFont("helvetica", "bold");
    doc.setFontSize(8);
    doc.setTextColor(248, 250, 252);
    doc.text("VERIFIED DOCUMENTS", margin, y);
    y += 6;

    documents.forEach((d) => {
      const statusIcon = d.ocr_status === "completed" ? "✓" : d.ocr_status === "processing" ? "…" : "—";
      doc.setFont("helvetica", "normal");
      doc.setFontSize(7);
      doc.setTextColor(148, 163, 184);
      doc.text(`${statusIcon}  ${d.document_type.replace(/_/g, " ").toUpperCase()}`, margin + 2, y);
      if (d.extracted_document_number) {
        doc.setTextColor(200, 210, 220);
        doc.text(`#${d.extracted_document_number}`, margin + 85, y);
      }
      if (d.confidence_score != null) {
        doc.setTextColor(74, 222, 128);
        doc.text(`${d.confidence_score}%`, W - margin - 2, y, { align: "right" });
      }
      y += 5;
    });

    y += 5;
  }

  // Disclaimers
  doc.setFillColor(17, 22, 43);
  doc.roundedRect(margin, y, contentW, 18, 2, 2, "F");
  doc.setFont("helvetica", "normal");
  doc.setFontSize(6);
  doc.setTextColor(100, 116, 139);
  const discLines = [
    "This report is generated by ATI Verify for remote document verification purposes only.",
    "It does not constitute a legal opinion, airworthiness determination, or physical aircraft inspection.",
    "All extracted data should be verified against original documents by a qualified professional.",
  ];
  discLines.forEach((line, i) => {
    doc.text(line, margin + 3, y + 5 + i * 4);
  });
  y += 22;

  // Digital signature placeholder
  doc.setDrawColor(100, 116, 139, 0.3);
  doc.setLineWidth(0.3);
  doc.line(margin + 60, y + 8, W - margin - 60, y + 8);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(7);
  doc.setTextColor(100, 116, 139);
  doc.text("Digital Signature", W / 2, y + 12, { align: "center" });
  doc.setFontSize(6);
  doc.text("Signed via ATI Verify · ABOS MarketSpace", W / 2, y + 16, { align: "center" });

  // Footer
  for (let p = 1; p <= doc.internal.getNumberOfPages(); p++) {
    doc.setPage(p);
    doc.setFontSize(6);
    doc.setTextColor(80, 90, 110);
    doc.text(`ATI Verify Report · ${session.session_code} · Page ${p} of ${doc.internal.getNumberOfPages()}`, margin, 290);
    doc.text("abos.aero", W - margin, 290, { align: "right" });
  }

  const filename = `ATI-Verify-${session.session_code}-${new Date().getFullYear()}.pdf`;
  doc.save(filename);
}