import { BadgeCheck, FileSearch, ShieldCheck } from "lucide-react";

export default function AdvisorStorySections() {
  return (
    <div className="mt-12 space-y-8">
      <section id="how-it-works" className="scroll-mt-24 rounded-2xl border border-border bg-card p-6 md:p-8"><p className="text-xs font-bold uppercase text-primary">How it works</p><h2 className="mt-2 text-2xl font-bold">From registration to decision in three steps</h2><div className="mt-6 grid gap-5 md:grid-cols-3">{[[FileSearch,"1. Identify","We match the registration across connected public aviation sources."],[ShieldCheck,"2. Verify","We expose evidence, data gaps, compliance and history signals."],[BadgeCheck,"3. Decide","Choose the depth of report needed for your transaction."]].map(([Icon,title,text]) => <div key={title} className="rounded-xl bg-muted p-5"><Icon className="h-6 w-6 text-primary" /><h3 className="mt-3 font-bold">{title}</h3><p className="mt-2 text-sm text-muted-foreground">{text}</p></div>)}</div></section>
      <section id="faq" className="scroll-mt-24 rounded-2xl border border-border bg-card p-6 md:p-8"><p className="text-xs font-bold uppercase text-primary">FAQ</p><h2 className="mt-2 text-2xl font-bold">Before you purchase</h2><div className="mt-5 divide-y divide-border">{[["Is this an official airworthiness decision?","No. ABOS consolidates evidence for due diligence; it does not replace an inspection or authority decision."],["Do I keep the report?","Yes. A purchased aircraft report remains available in My Reports."],["Can I add private documents?","Yes. Add listing text and supporting files before checkout; they are attached privately to the report."]].map(([q,a]) => <details key={q} className="group py-4"><summary className="cursor-pointer font-bold">{q}</summary><p className="mt-2 max-w-3xl text-sm text-muted-foreground">{a}</p></details>)}</div></section>
      <section id="trust" className="scroll-mt-24 rounded-2xl bg-secondary p-6 text-secondary-foreground md:flex md:items-center md:justify-between md:p-8"><div><p className="text-xs font-bold uppercase text-primary">About ABOS</p><h2 className="mt-2 text-2xl font-bold">Aviation intelligence, not a marketplace promise.</h2><p className="mt-2 max-w-2xl text-sm text-secondary-foreground/70">We distinguish public-source evidence from licensed intelligence and clearly show what could not be verified.</p></div><div className="mt-5 flex gap-4 text-xs font-bold text-primary md:mt-0"><span>Source-led</span><span>Owner-masked</span><span>Decision-ready</span></div></section>
    </div>
  );
}