import { useState } from "react";
import { useQuery } from "@tanstack/react-query";
import { base44 } from "@/api/base44Client";
import { useLocation } from "react-router-dom";
import { FileText, Download, ChevronDown, ChevronUp } from "lucide-react";
import MiniGlobe from "@/components/MiniGlobe";
import { cleanAircraftMake } from "@/lib/cleanAircraftMake";

const DIMS = [
  { key: "documentation",      label: "Documentation & Records" },
  { key: "technical",          label: "Technical Condition" },
  { key: "transparency",       label: "Seller Transparency" },
  { key: "transaction_ready",  label: "Transaction Readiness" },
  { key: "usage_mission",      label: "Usage & Mission" },
  { key: "storage_exposure",   label: "Storage & Exposure" },
  { key: "config_clarity",     label: "Configuration Clarity" },
  { key: "market_readiness",   label: "Market Readiness" },
];

function verdictFor(total) {
  if (total >= 100) return { label: "EXCEPTIONAL",  color: "#00f5ff" };
  if (total >= 85)  return { label: "STRONG BUY",   color: "#0F7A56" };
  if (total >= 65)  return { label: "FAIR",          color: "#D4A017" };
  if (total >= 45)  return { label: "CAUTION",       color: "#E8762D" };
  if (total >= 20)  return { label: "RED FLAGS",     color: "#C0392B" };
  return               { label: "AVOID",         color: "#7f0000" };
}

function genCode(reg, score) {
  const chars = "ABCDEFGHJKLMNPQRSTUVWXYZ23456789";
  let suffix = "";
  for (let i = 0; i < 5; i++) suffix += chars[Math.floor(Math.random() * chars.length)];
  const r = (reg || "NREG").replace(/[^A-Z0-9]/gi, "").toUpperCase().slice(0, 6);
  return `ATI-${r}-${score}-${suffix}`;
}

async function exportDocx(report, code) {
  // Dynamically build a simple DOCX using the docx library if available, fallback to text blob
  const lines = [];
  lines.push("ATI REPORT powered by ABOS — Aircraft Buy Or Sell, since 2021");
  lines.push("=" .repeat(64));
  lines.push(`Report Code: ${code}`);
  lines.push(`Generated: ${new Date().toLocaleDateString("en-GB", { day: "numeric", month: "long", year: "numeric" })}`);
  lines.push("");
  lines.push("AIRCRAFT IDENTITY");
  lines.push("-".repeat(40));
  (report.identity_rows || []).forEach(r => lines.push(`${r.label}: ${r.value}`));
  lines.push("");
  lines.push(`ATI TOTAL SCORE: ${report.total} / 120`);
  lines.push(`VERDICT: ${verdictFor(report.total).label}`);
  lines.push(`DEAL SCORE: ${((report.total / 120) * 10).toFixed(1)} / 10`);
  lines.push("");
  lines.push("DIMENSION SCORES");
  lines.push("-".repeat(40));
  DIMS.forEach(d => {
    const s = report[d.key] || 0;
    lines.push(`${d.label}: ${s}/15`);
    if (report.reasons?.[d.key]) lines.push(`  → ${report.reasons[d.key]}`);
  });
  lines.push("");
  lines.push("EXECUTIVE SUMMARY");
  lines.push("-".repeat(40));
  lines.push(report.summary || "");
  lines.push("");
  lines.push("KEY STRENGTHS");
  lines.push("-".repeat(40));
  (report.strengths || []).forEach(s => lines.push(`• ${s}`));
  lines.push("");
  lines.push("RISK FACTORS");
  lines.push("-".repeat(40));
  (report.risks || []).forEach(r => lines.push(`• ${r}`));
  lines.push("");
  lines.push("RECOMMENDATIONS");
  lines.push("-".repeat(40));
  (report.recommendations || []).forEach(r => lines.push(`• ${r}`));
  lines.push("");
  lines.push("─".repeat(64));
  lines.push("This report is generated by ABOS MarketSpace Aviation Intelligence.");
  lines.push("ABOS — Aircraft Buy Or Sell — since 2021.");

  const blob = new Blob([lines.join("\n")], { type: "application/vnd.openxmlformats-officedocument.wordprocessingml.document" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = `${code}.docx`;
  a.click();
  URL.revokeObjectURL(url);
}

function DimRow({ label, score, reason }) {
  const color = score >= 13 ? "#00f5ff" : score >= 10 ? "#0F7A56" : score >= 7 ? "#D4A017" : "#C0392B";
  const pct = (score / 15) * 100;
  return (
    <div className="py-3 border-b border-white/[0.06] last:border-0">
      <div className="flex items-center justify-between mb-1.5">
        <span className="text-[12px] font-bold text-white/80">{label}</span>
        <span className="text-[14px] font-black" style={{ color }}>{score}<span className="text-white/30 text-[10px]">/15</span></span>
      </div>
      <div className="h-1.5 rounded-full bg-white/10 overflow-hidden mb-1.5">
        <div className="h-full rounded-full" style={{ width: `${pct}%`, backgroundColor: color }} />
      </div>
      {reason && <p className="text-[11px] text-white/40 leading-snug">{reason}</p>}
    </div>
  );
}

function BulletList({ items, color = "#00f5ff" }) {
  if (!items?.length) return <p className="text-white/30 text-[12px]">None identified.</p>;
  return (
    <ul className="space-y-1.5">
      {items.map((item, i) => (
        <li key={i} className="flex items-start gap-2 text-[13px] text-white/70 leading-snug">
          <span className="mt-1.5 w-1.5 h-1.5 rounded-full shrink-0" style={{ backgroundColor: color }} />
          {item}
        </li>
      ))}
    </ul>
  );
}

export default function ATIFullReport() {
  const location = useLocation();
  const params = new URLSearchParams(location.search);
  const prefillId = params.get("listing");

  const [input, setInput] = useState("");
  const [result, setResult] = useState(null);
  const [reportCode, setReportCode] = useState(null);
  const [loading, setLoading] = useState(false);
  const [showPicker, setShowPicker] = useState(false);
  const [regExtracted, setRegExtracted] = useState("");

  const { data: listings = [] } = useQuery({
    queryKey: ["listings-active"],
    queryFn: () => base44.entities.AircraftListing.filter({ status: "active" }),
  });

  function prefillFromListing(l) {
    const make = cleanAircraftMake(l.make);
    const lines = [
      `${l.year || ""} ${make} ${l.model || ""}`.trim(),
      l.registration ? `Registration: ${l.registration}` : "",
      l.total_time != null ? `Airframe Total Time: ${l.total_time} hrs` : "",
      l.engine_hours != null ? `Engine SMOH: ${l.engine_hours} hrs` : "",
      l.tbo != null ? `TBO: ${l.tbo} hrs` : "",
      l.last_annual ? `Last Annual: ${l.last_annual}` : "",
      l.avionics ? `Avionics: ${l.avionics}` : "",
      l.asking_price != null ? `Asking Price: $${l.asking_price.toLocaleString()}` : "",
      l.ai_summary ? `Additional notes: ${l.ai_summary}` : "",
    ].filter(Boolean);
    setInput(lines.join("\n"));
    setRegExtracted(l.registration || "");
    setShowPicker(false);
    setResult(null);
    setReportCode(null);
  }

  async function handleGenerate() {
    if (!input.trim()) return;
    setLoading(true);
    setResult(null);
    try {
      const res = await base44.integrations.Core.InvokeLLM({
        prompt: `You are ABOS — Aircraft Buy Or Sell — an expert aviation appraisal engine. Generate a professional ATI Full Report for the following aircraft.

AIRCRAFT DATA:
${input}

Score each of 8 dimensions 0–15 and write a professional narrative report. Be precise, concise, and actionable. Write like a senior aviation appraiser.

Return ONLY valid JSON with this exact schema:
{
  "documentation": number,
  "technical": number,
  "transparency": number,
  "transaction_ready": number,
  "usage_mission": number,
  "storage_exposure": number,
  "config_clarity": number,
  "market_readiness": number,
  "reasons": {
    "documentation": "one-line reason",
    "technical": "one-line reason",
    "transparency": "one-line reason",
    "transaction_ready": "one-line reason",
    "usage_mission": "one-line reason",
    "storage_exposure": "one-line reason",
    "config_clarity": "one-line reason",
    "market_readiness": "one-line reason"
  },
  "identity_rows": [
    { "label": "Registration", "value": "..." },
    { "label": "Year", "value": "..." },
    { "label": "Make / Model", "value": "..." },
    { "label": "Airframe TT", "value": "..." },
    { "label": "Engine SMOH", "value": "..." },
    { "label": "TBO", "value": "..." },
    { "label": "Last Annual", "value": "..." },
    { "label": "Avionics", "value": "..." },
    { "label": "Asking Price", "value": "..." }
  ],
  "omvm_low": number,
  "omvm_high": number,
  "asking_price": number or null,
  "summary": "3–4 sentence executive summary of the aircraft and transaction opportunity",
  "strengths": ["bullet 1", "bullet 2", "bullet 3"],
  "risks": ["bullet 1", "bullet 2"],
  "recommendations": ["bullet 1", "bullet 2", "bullet 3"],
  "registration_extracted": "N-number or registration extracted from data"
}`,
        response_json_schema: {
          type: "object",
          properties: {
            documentation: { type: "number" },
            technical: { type: "number" },
            transparency: { type: "number" },
            transaction_ready: { type: "number" },
            usage_mission: { type: "number" },
            storage_exposure: { type: "number" },
            config_clarity: { type: "number" },
            market_readiness: { type: "number" },
            reasons: { type: "object" },
            identity_rows: { type: "array" },
            omvm_low: { type: "number" },
            omvm_high: { type: "number" },
            asking_price: {},
            summary: { type: "string" },
            strengths: { type: "array" },
            risks: { type: "array" },
            recommendations: { type: "array" },
            registration_extracted: { type: "string" },
          },
        },
      });

      const total =
        (res.documentation || 0) + (res.technical || 0) + (res.transparency || 0) +
        (res.transaction_ready || 0) + (res.usage_mission || 0) + (res.storage_exposure || 0) +
        (res.config_clarity || 0) + (res.market_readiness || 0);

      const reg = regExtracted || res.registration_extracted || "NREG";
      const code = genCode(reg, total);
      setResult({ ...res, total });
      setReportCode(code);
    } catch (e) {
      console.error(e);
    }
    setLoading(false);
  }

  const verdict = result ? verdictFor(result.total) : null;
  const dealScore = result ? ((result.total / 120) * 10).toFixed(1) : null;
  const omvmMid = result ? Math.round((result.omvm_low + result.omvm_high) / 2) : null;
  const priceDiff = result?.asking_price && omvmMid
    ? (((omvmMid - result.asking_price) / omvmMid) * 100).toFixed(1)
    : null;

  return (
    <div className="min-h-screen" style={{ background: "#0A081E" }}>
      {/* Header */}
      <div className="px-4 md:px-8 pt-8 pb-6 border-b border-white/[0.07]">
        <p className="text-[9px] uppercase tracking-[0.3em] font-black mb-1" style={{ color: "#D4A017" }}>
          ATI Tool 2 · Pro
        </p>
        <h1 className="text-3xl md:text-4xl font-black uppercase tracking-tight text-white leading-tight">
          ATI Full Report
        </h1>
        <p className="text-white/45 text-[12px] mt-2">
          Professional aircraft appraisal with narrative, scoring, valuation and .docx export.
        </p>
      </div>

      <div className="px-4 md:px-8 py-6 grid lg:grid-cols-[1fr_560px] gap-6 items-start">
        {/* Input */}
        <div>
          <div className="mb-4">
            <button
              onClick={() => setShowPicker(v => !v)}
              className="flex items-center gap-2 text-[11px] font-bold px-4 py-2 rounded-lg border border-white/[0.12] text-white/60 hover:text-white hover:border-white/20 transition-colors"
            >
              Load from saved listing {showPicker ? <ChevronUp className="w-3.5 h-3.5" /> : <ChevronDown className="w-3.5 h-3.5" />}
            </button>
            {showPicker && listings.length > 0 && (
              <div className="mt-2 rounded-xl border border-white/[0.1] overflow-hidden max-h-56 overflow-y-auto"
                style={{ background: "rgba(255,255,255,0.04)", backdropFilter: "blur(16px)" }}>
                {listings.map(l => (
                  <button key={l.id} onClick={() => prefillFromListing(l)}
                    className="w-full flex items-center justify-between px-4 py-2.5 border-b border-white/[0.06] last:border-0 hover:bg-white/[0.06] transition-colors text-left">
                    <span className="text-[12px] text-white font-semibold">{l.year} {cleanAircraftMake(l.make)} {l.model}</span>
                    <span className="text-[10px] text-white/35 font-mono">{l.registration || "—"}</span>
                  </button>
                ))}
              </div>
            )}
          </div>

          <textarea
            value={input}
            onChange={e => setInput(e.target.value)}
            placeholder={`Paste full aircraft details for a professional appraisal report…\n\nInclude:\n- Make, model, year, registration\n- Airframe TT, engine SMOH, TBO\n- Avionics, modifications, STCs\n- Maintenance history, AD compliance\n- Storage, annual status\n- Asking price\n- Seller notes, condition description`}
            rows={18}
            className="w-full rounded-xl px-4 py-3 text-[13px] leading-relaxed resize-none focus:outline-none"
            style={{
              background: "rgba(255,255,255,0.05)",
              border: "1px solid rgba(255,255,255,0.12)",
              color: "rgba(255,255,255,0.9)",
            }}
          />
          <button
            onClick={handleGenerate}
            disabled={loading || !input.trim()}
            className="mt-4 w-full flex items-center justify-center gap-2 py-3.5 rounded-xl font-black text-[13px] uppercase tracking-widest transition-all active:scale-98 disabled:opacity-40"
            style={{
              background: "rgba(212,160,23,0.12)",
              border: "1px solid rgba(212,160,23,0.40)",
              color: "#D4A017",
            }}
          >
            <FileText className="w-4 h-4" />
            {loading ? "Generating Report…" : "Generate ATI Full Report"}
          </button>
        </div>

        {/* Report output */}
        <div>
          {!result && !loading && (
            <div className="rounded-2xl border border-white/[0.07] p-8 text-center"
              style={{ background: "rgba(255,255,255,0.03)" }}>
              <FileText className="w-10 h-10 mx-auto mb-3 text-white/20" />
              <p className="text-white/30 text-sm">Your professional ATI report will appear here</p>
            </div>
          )}

          {loading && (
            <div className="rounded-2xl border border-white/[0.07] p-8 text-center"
              style={{ background: "rgba(255,255,255,0.03)" }}>
              <MiniGlobe size={40} label="Generating professional ATI report…" color="#D4A017" />
            </div>
          )}

          {result && verdict && (
            <div className="rounded-2xl overflow-hidden border border-white/[0.12]"
              style={{ background: "rgba(255,255,255,0.04)", backdropFilter: "blur(28px)" }}>

              {/* Report header — ABOS branded */}
              <div className="px-6 py-5 border-b border-white/[0.08]"
                style={{ background: "linear-gradient(135deg, rgba(27,42,74,0.9) 0%, rgba(10,8,30,0.95) 100%)" }}>
                <p className="text-[#D4A017] text-[9px] uppercase tracking-[0.25em] font-black">
                  ATI REPORT powered by ABOS — Aircraft Buy Or Sell, since 2021
                </p>
                <div className="flex items-end justify-between mt-3 gap-4">
                  <div>
                    <p className="text-white font-black text-2xl leading-tight">{result.total}<span className="text-white/30 text-sm">/120</span></p>
                    <div className="flex items-center gap-2 mt-1">
                      <span className="text-[10px] font-black uppercase tracking-wider px-2.5 py-0.5 rounded-full"
                        style={{ background: `${verdict.color}18`, border: `1px solid ${verdict.color}35`, color: verdict.color }}>
                        {verdict.label}
                      </span>
                      <span className="text-white/40 text-[10px]">Deal Score: <span className="font-black text-white/70">{dealScore}/10</span></span>
                    </div>
                  </div>
                  {reportCode && (
                    <div className="text-right">
                      <p className="text-[9px] text-white/30 uppercase tracking-wider">Report Code</p>
                      <p className="font-mono text-[#D4A017] text-[11px] font-bold">{reportCode}</p>
                    </div>
                  )}
                </div>
                {/* Score bar */}
                <div className="mt-3 h-1.5 rounded-full bg-white/10 overflow-hidden">
                  <div className="h-full rounded-full"
                    style={{ width: `${(result.total / 120) * 100}%`, background: `linear-gradient(90deg, #1B2A4A, ${verdict.color})` }} />
                </div>
              </div>

              {/* Identity table */}
              {result.identity_rows?.length > 0 && (
                <div className="px-5 py-4 border-b border-white/[0.07]">
                  <p className="text-[9px] uppercase tracking-[0.2em] text-white/30 font-black mb-3">Aircraft Identity</p>
                  <div className="grid grid-cols-2 gap-x-6 gap-y-1.5">
                    {result.identity_rows.map(r => (
                      <div key={r.label} className="flex justify-between gap-2 py-1 border-b border-white/[0.04] last:border-0">
                        <span className="text-[10px] text-white/35 shrink-0">{r.label}</span>
                        <span className="text-[10px] text-white/75 font-semibold text-right truncate">{r.value}</span>
                      </div>
                    ))}
                  </div>
                </div>
              )}

              {/* Valuation */}
              {omvmMid && (
                <div className="px-5 py-4 border-b border-white/[0.07] grid grid-cols-3 gap-4">
                  <div>
                    <p className="text-[9px] text-white/30 uppercase tracking-wider font-semibold">OMVM Range</p>
                    <p className="text-[11px] font-black text-white/75">${result.omvm_low.toLocaleString()} – ${result.omvm_high.toLocaleString()}</p>
                  </div>
                  <div>
                    <p className="text-[9px] text-white/30 uppercase tracking-wider font-semibold">Midpoint</p>
                    <p className="text-[11px] font-black text-white">${omvmMid.toLocaleString()}</p>
                  </div>
                  <div>
                    <p className="text-[9px] text-white/30 uppercase tracking-wider font-semibold">vs Market</p>
                    {priceDiff ? (
                      <p className="text-[11px] font-black" style={{ color: parseFloat(priceDiff) >= 0 ? "#0F7A56" : "#C0392B" }}>
                        {parseFloat(priceDiff) >= 0 ? "▼" : "▲"} {Math.abs(parseFloat(priceDiff))}%
                      </p>
                    ) : <p className="text-[11px] text-white/30">—</p>}
                  </div>
                </div>
              )}

              {/* Dimension scores */}
              <div className="px-5 py-4 border-b border-white/[0.07]">
                <p className="text-[9px] uppercase tracking-[0.2em] text-white/30 font-black mb-3">Dimension Scores</p>
                {DIMS.map(d => (
                  <DimRow key={d.key} label={d.label} score={result[d.key] || 0} reason={result.reasons?.[d.key]} />
                ))}
              </div>

              {/* Narrative */}
              <div className="px-5 py-4 border-b border-white/[0.07]">
                <p className="text-[9px] uppercase tracking-[0.2em] text-white/30 font-black mb-2">Executive Summary</p>
                <p className="text-[13px] text-white/70 leading-relaxed">{result.summary}</p>
              </div>

              <div className="grid md:grid-cols-2 divide-y md:divide-y-0 md:divide-x divide-white/[0.07] border-b border-white/[0.07]">
                <div className="px-5 py-4">
                  <p className="text-[9px] uppercase tracking-[0.2em] font-black mb-3" style={{ color: "#00f5ff" }}>Key Strengths</p>
                  <BulletList items={result.strengths} color="#00f5ff" />
                </div>
                <div className="px-5 py-4">
                  <p className="text-[9px] uppercase tracking-[0.2em] font-black mb-3" style={{ color: "#C0392B" }}>Risk Factors</p>
                  <BulletList items={result.risks} color="#C0392B" />
                </div>
              </div>

              <div className="px-5 py-4 border-b border-white/[0.07]">
                <p className="text-[9px] uppercase tracking-[0.2em] font-black mb-3" style={{ color: "#D4A017" }}>Recommendations</p>
                <BulletList items={result.recommendations} color="#D4A017" />
              </div>

              {/* Export */}
              <div className="px-5 py-4 flex items-center justify-between gap-4">
                <p className="text-[10px] text-white/30 font-mono">{reportCode}</p>
                <button
                  onClick={() => exportDocx(result, reportCode)}
                  className="flex items-center gap-2 px-5 py-2.5 rounded-xl font-black text-[11px] uppercase tracking-wider transition-all hover:opacity-90 active:scale-98"
                  style={{ background: "rgba(212,160,23,0.12)", border: "1px solid rgba(212,160,23,0.35)", color: "#D4A017" }}
                >
                  <Download className="w-4 h-4" />
                  Export .docx
                </button>
              </div>
            </div>
          )}
        </div>
      </div>
    </div>
  );
}