import { useState } from "react";
import { useQuery } from "@tanstack/react-query";
import { base44 } from "@/api/base44Client";
import { useLocation } from "react-router-dom";
import { FileText, Download, ChevronDown, ChevronUp } from "lucide-react";
import MiniGlobe from "@/components/MiniGlobe";
import { cleanAircraftMake } from "@/lib/cleanAircraftMake";
import { T, atiBand, atiDimColor } from "@/theme/atiPremium";

const DIMS = [
  { key: "documentation",      label: "Documentation & Records" },
  { key: "technical",          label: "Technical Condition" },
  { key: "transparency",       label: "Seller Transparency" },
  { key: "transaction_ready",  label: "Transaction Readiness" },
  { key: "usage_mission",      label: "Usage & Mission" },
  { key: "storage_exposure",   label: "Storage & Exposure" },
  { key: "config_clarity",     label: "Configuration Clarity" },
  { key: "market_readiness",   label: "Market Readiness" },
];

// ATI Premium bands + dimension colors (isolated in theme/atiPremium.js)
const verdictFor = atiBand;
const dimColor = atiDimColor;

function genCode(reg, score) {
  const chars = "ABCDEFGHJKLMNPQRSTUVWXYZ23456789";
  let suffix = "";
  for (let i = 0; i < 5; i++) suffix += chars[Math.floor(Math.random() * chars.length)];
  const r = (reg || "NREG").replace(/[^A-Z0-9]/gi, "").toUpperCase().slice(0, 6);
  return `ATI-${r}-${score}-${suffix}`;
}

async function exportDocx(report, code) {
  const lines = [];
  lines.push("ATI REPORT powered by ABOS — Aircraft Buy Or Sell, since 2021");
  lines.push("=".repeat(64));
  lines.push(`Report Code: ${code}`);
  lines.push(`Generated: ${new Date().toLocaleDateString("en-GB", { day: "numeric", month: "long", year: "numeric" })}`);
  lines.push("");
  lines.push("AIRCRAFT IDENTITY");
  lines.push("-".repeat(40));
  (report.identity_rows || []).forEach(r => lines.push(`${r.label}: ${r.value}`));
  lines.push("");
  lines.push(`ATI TOTAL SCORE: ${report.total} / 120`);
  lines.push(`VERDICT: ${verdictFor(report.total).label}`);
  lines.push(`DEAL SCORE: ${((report.total / 120) * 10).toFixed(1)} / 10`);
  lines.push("");
  lines.push("DIMENSION SCORES");
  lines.push("-".repeat(40));
  DIMS.forEach(d => {
    const s = report[d.key] || 0;
    lines.push(`${d.label}: ${s}/15`);
    if (report.reasons?.[d.key]) lines.push(`  → ${report.reasons[d.key]}`);
  });
  lines.push("");
  lines.push("EXECUTIVE SUMMARY");
  lines.push("-".repeat(40));
  lines.push(report.summary || "");
  lines.push("");
  lines.push("KEY STRENGTHS");
  lines.push("-".repeat(40));
  (report.strengths || []).forEach(s => lines.push(`• ${s}`));
  lines.push("");
  lines.push("RISK FACTORS");
  lines.push("-".repeat(40));
  (report.risks || []).forEach(r => lines.push(`• ${r}`));
  lines.push("");
  lines.push("RECOMMENDATIONS");
  lines.push("-".repeat(40));
  (report.recommendations || []).forEach(r => lines.push(`• ${r}`));
  lines.push("");
  lines.push("─".repeat(64));
  lines.push("This report is generated by ABOS MarketSpace Aviation Intelligence.");
  lines.push("ABOS — Aircraft Buy Or Sell — since 2021.");

  const blob = new Blob([lines.join("\n")], { type: "application/vnd.openxmlformats-officedocument.wordprocessingml.document" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = `${code}.docx`;
  a.click();
  URL.revokeObjectURL(url);
}

// ─── Sub-components ───────────────────────────────────────────────

function Label({ children, color = T.w3, style = {} }) {
  return (
    <p style={{ fontSize: "9px", fontWeight: 600, letterSpacing: "0.12em", textTransform: "uppercase", color, margin: 0, ...style }}>
      {children}
    </p>
  );
}

function DimRow({ label, score, reason }) {
  const color = dimColor(score);
  const pct = (score / 15) * 100;
  return (
    <div style={{ marginBottom: "10px" }}>
      <div style={{ display: "flex", justifyContent: "space-between", marginBottom: "4px" }}>
        <span style={{ fontSize: "11px", color: T.w2 }}>{label}</span>
        <span style={{ fontSize: "11px", fontWeight: 600, color, fontVariantNumeric: "tabular-nums" }}>
          {score}<span style={{ color: T.w3, fontWeight: 400 }}>/15</span>
        </span>
      </div>
      <div style={{ height: "3px", borderRadius: "99px", background: T.w4, overflow: "hidden" }}>
        <div style={{ height: "100%", width: `${pct}%`, background: color, borderRadius: "99px", transition: "width 0.4s cubic-bezier(0.16,1,0.3,1)" }} />
      </div>
      {reason && <p style={{ fontSize: "10px", color: T.w3, marginTop: "3px", lineHeight: 1.5 }}>{reason}</p>}
    </div>
  );
}

function BulletList({ items, color = T.teal }) {
  if (!items?.length) return <p style={{ color: T.w3, fontSize: "12px", margin: 0 }}>None identified.</p>;
  return (
    <ul style={{ listStyle: "none", padding: 0, margin: 0, display: "flex", flexDirection: "column", gap: "6px" }}>
      {items.map((item, i) => (
        <li key={i} style={{ display: "flex", gap: "8px", alignItems: "flex-start" }}>
          <span style={{ flexShrink: 0, marginTop: "2px", width: "5px", height: "5px", borderRadius: "50%", background: color, opacity: 0.7 }} />
          <span style={{ fontSize: "12px", color: T.w2, lineHeight: 1.6 }}>{item}</span>
        </li>
      ))}
    </ul>
  );
}

// ─── Page ─────────────────────────────────────────────────────────

export default function ATIFullReport() {
  const location = useLocation();
  const params = new URLSearchParams(location.search);
  const prefillId = params.get("listing");

  const [input, setInput] = useState("");
  const [result, setResult] = useState(null);
  const [reportCode, setReportCode] = useState(null);
  const [loading, setLoading] = useState(false);
  const [showPicker, setShowPicker] = useState(false);
  const [regExtracted, setRegExtracted] = useState("");

  const { data: listings = [] } = useQuery({
    queryKey: ["listings-active"],
    queryFn: () => base44.entities.AircraftListing.filter({ status: "active" }),
  });

  function prefillFromListing(l) {
    const make = cleanAircraftMake(l.make);
    const lines = [
      `${l.year || ""} ${make} ${l.model || ""}`.trim(),
      l.registration ? `Registration: ${l.registration}` : "",
      l.total_time != null ? `Airframe Total Time: ${l.total_time} hrs` : "",
      l.engine_hours != null ? `Engine SMOH: ${l.engine_hours} hrs` : "",
      l.tbo != null ? `TBO: ${l.tbo} hrs` : "",
      l.last_annual ? `Last Annual: ${l.last_annual}` : "",
      l.avionics ? `Avionics: ${l.avionics}` : "",
      l.asking_price != null ? `Asking Price: $${l.asking_price.toLocaleString()}` : "",
      l.ai_summary ? `Additional notes: ${l.ai_summary}` : "",
    ].filter(Boolean);
    setInput(lines.join("\n"));
    setRegExtracted(l.registration || "");
    setShowPicker(false);
    setResult(null);
    setReportCode(null);
  }

  async function handleGenerate() {
    if (!input.trim()) return;
    setLoading(true);
    setResult(null);
    try {
      const res = await base44.integrations.Core.InvokeLLM({
        prompt: `You are ABOS — Aircraft Buy Or Sell — an expert aviation appraisal engine. Generate a professional ATI Full Report for the following aircraft.

AIRCRAFT DATA:
${input}

Score each of 8 dimensions 0–15 and write a professional narrative report. Be precise, concise, and actionable. Write like a senior aviation appraiser.

Return ONLY valid JSON with this exact schema:
{
  "documentation": number,
  "technical": number,
  "transparency": number,
  "transaction_ready": number,
  "usage_mission": number,
  "storage_exposure": number,
  "config_clarity": number,
  "market_readiness": number,
  "reasons": {
    "documentation": "one-line reason",
    "technical": "one-line reason",
    "transparency": "one-line reason",
    "transaction_ready": "one-line reason",
    "usage_mission": "one-line reason",
    "storage_exposure": "one-line reason",
    "config_clarity": "one-line reason",
    "market_readiness": "one-line reason"
  },
  "identity_rows": [
    { "label": "Registration", "value": "..." },
    { "label": "Year", "value": "..." },
    { "label": "Make / Model", "value": "..." },
    { "label": "Airframe TT", "value": "..." },
    { "label": "Engine SMOH", "value": "..." },
    { "label": "TBO", "value": "..." },
    { "label": "Last Annual", "value": "..." },
    { "label": "Avionics", "value": "..." },
    { "label": "Asking Price", "value": "..." }
  ],
  "omvm_low": number,
  "omvm_high": number,
  "asking_price": number or null,
  "summary": "3–4 sentence executive summary of the aircraft and transaction opportunity",
  "strengths": ["bullet 1", "bullet 2", "bullet 3"],
  "risks": ["bullet 1", "bullet 2"],
  "recommendations": ["bullet 1", "bullet 2", "bullet 3"],
  "registration_extracted": "N-number or registration extracted from data"
}`,
        response_json_schema: {
          type: "object",
          properties: {
            documentation: { type: "number" },
            technical: { type: "number" },
            transparency: { type: "number" },
            transaction_ready: { type: "number" },
            usage_mission: { type: "number" },
            storage_exposure: { type: "number" },
            config_clarity: { type: "number" },
            market_readiness: { type: "number" },
            reasons: { type: "object" },
            identity_rows: { type: "array" },
            omvm_low: { type: "number" },
            omvm_high: { type: "number" },
            asking_price: {},
            summary: { type: "string" },
            strengths: { type: "array" },
            risks: { type: "array" },
            recommendations: { type: "array" },
            registration_extracted: { type: "string" },
          },
        },
      });

      const total =
        (res.documentation || 0) + (res.technical || 0) + (res.transparency || 0) +
        (res.transaction_ready || 0) + (res.usage_mission || 0) + (res.storage_exposure || 0) +
        (res.config_clarity || 0) + (res.market_readiness || 0);

      const reg = regExtracted || res.registration_extracted || "NREG";
      const code = genCode(reg, total);
      setResult({ ...res, total });
      setReportCode(code);
    } catch (e) {
      console.error(e);
    }
    setLoading(false);
  }

  const verdict = result ? verdictFor(result.total) : null;
  const dealScore = result ? ((result.total / 120) * 10).toFixed(1) : null;
  const omvmMid = result ? Math.round((result.omvm_low + result.omvm_high) / 2) : null;
  const priceDiff = result?.asking_price && omvmMid
    ? (((omvmMid - result.asking_price) / omvmMid) * 100).toFixed(1)
    : null;

  const canGenerate = !!input.trim() && !loading;

  return (
    <div style={{
      minHeight: "100vh",
      background: T.ink,
      backgroundImage: "radial-gradient(circle, rgba(255,255,255,0.09) 1.5px, transparent 1.5px)",
      backgroundSize: "40px 40px",
      color: T.w1,
    }}>
      {/* Ambient amber glow */}
      <div aria-hidden style={{
        position: "fixed", top: "-200px", left: "50%", transform: "translateX(-50%)",
        width: "700px", height: "400px",
        background: "radial-gradient(ellipse, rgba(245,194,66,0.06), transparent 70%)",
        pointerEvents: "none", zIndex: 0,
      }} />

      {/* Header */}
      <div style={{ position: "relative", zIndex: 1, padding: "32px 32px 24px", borderBottom: `0.5px solid ${T.border}` }}>
        <Label color={T.amber} style={{ marginBottom: "8px" }}>ATI Tool 2 · Pro</Label>
        <h1 style={{ fontSize: "clamp(24px,4vw,36px)", fontWeight: 500, letterSpacing: "-0.04em", lineHeight: 1.06, color: T.w1, margin: 0 }}>
          ATI <span style={{ color: T.amber }}>Full Report</span>
        </h1>
        <p style={{ color: T.w3, fontSize: "12px", marginTop: "8px" }}>
          Professional aircraft appraisal with narrative, scoring, valuation and .docx export.
        </p>
      </div>

      <div style={{ position: "relative", zIndex: 1, padding: "24px 32px" }}
        className="grid grid-cols-1 lg:grid-cols-[1fr_560px] gap-6 items-start">

        {/* Input */}
        <div>
          {listings.length > 0 && (
            <div style={{ marginBottom: "16px" }}>
              <button
                onClick={() => setShowPicker(v => !v)}
                style={{
                  display: "inline-flex", alignItems: "center", gap: "6px",
                  fontSize: "11px", fontWeight: 600, padding: "7px 14px", borderRadius: "8px",
                  background: "transparent", border: `0.5px solid ${T.border}`, color: T.w3,
                  cursor: "pointer", transition: "border-color 0.15s, color 0.15s",
                }}
                onMouseEnter={(e) => { e.currentTarget.style.borderColor = T.borderMd; e.currentTarget.style.color = T.w1; }}
                onMouseLeave={(e) => { e.currentTarget.style.borderColor = T.border; e.currentTarget.style.color = T.w3; }}
              >
                Load from saved listing
                {showPicker ? <ChevronUp size={12} /> : <ChevronDown size={12} />}
              </button>

              {showPicker && (
                <div style={{
                  marginTop: "8px", background: "rgba(255,255,255,0.04)", border: `0.5px solid ${T.border}`,
                  borderRadius: "10px", overflow: "hidden", maxHeight: "220px", overflowY: "auto",
                }}>
                  {listings.map(l => (
                    <button key={l.id} onClick={() => prefillFromListing(l)}
                      style={{
                        display: "flex", width: "100%", alignItems: "center", justifyContent: "space-between",
                        padding: "10px 16px", borderBottom: `0.5px solid ${T.border}`, background: "transparent",
                        borderLeft: "none", borderRight: "none", borderTop: "none", cursor: "pointer",
                        textAlign: "left", transition: "background 0.1s",
                      }}
                      onMouseEnter={(e) => { e.currentTarget.style.background = "rgba(255,255,255,0.04)"; }}
                      onMouseLeave={(e) => { e.currentTarget.style.background = "transparent"; }}
                    >
                      <span style={{ fontSize: "12px", color: T.w1, fontWeight: 500 }}>
                        {l.year} {cleanAircraftMake(l.make)} {l.model}
                      </span>
                      <span style={{ fontSize: "10px", color: T.w3, fontFamily: "'Courier New', monospace", letterSpacing: "0.06em" }}>
                        {l.registration || "—"}
                      </span>
                    </button>
                  ))}
                </div>
              )}
            </div>
          )}

          <textarea
            value={input}
            onChange={e => setInput(e.target.value)}
            placeholder={`Paste full aircraft details for a professional appraisal report…\n\nInclude:\n- Make, model, year, registration\n- Airframe TT, engine SMOH, TBO\n- Avionics, modifications, STCs\n- Maintenance history, AD compliance\n- Storage, annual status\n- Asking price\n- Seller notes, condition description`}
            rows={18}
            style={{
              width: "100%", boxSizing: "border-box", background: "rgba(255,255,255,0.04)",
              border: `0.5px solid ${T.border}`, borderRadius: "10px", color: T.w1, outline: "none",
              padding: "14px 16px", fontSize: "13px", lineHeight: 1.7, resize: "vertical",
              fontFamily: "inherit", transition: "border-color 0.15s, background 0.15s",
            }}
            onFocus={(e) => { e.target.style.borderColor = T.amberBdr; e.target.style.background = "rgba(245,194,66,0.03)"; }}
            onBlur={(e) => { e.target.style.borderColor = T.border; e.target.style.background = "rgba(255,255,255,0.04)"; }}
          />

          <button
            onClick={handleGenerate}
            disabled={!canGenerate}
            style={{
              marginTop: "14px", width: "100%", display: "flex", alignItems: "center", justifyContent: "center",
              gap: "8px", padding: "13px 0", borderRadius: "8px",
              background: canGenerate ? T.amber : "rgba(255,255,255,0.05)",
              border: canGenerate ? "none" : `0.5px solid ${T.border}`,
              color: canGenerate ? T.ink : T.w3, fontWeight: 600, fontSize: "13px",
              letterSpacing: "-0.01em", cursor: canGenerate ? "pointer" : "default",
              transition: "background 0.15s", opacity: canGenerate ? 1 : 0.6,
            }}
            onMouseEnter={(e) => { if (canGenerate) e.currentTarget.style.background = T.amberHov; }}
            onMouseLeave={(e) => { if (canGenerate) e.currentTarget.style.background = T.amber; }}
          >
            <FileText size={15} />
            {loading ? "Generating Report…" : "Generate ATI Full Report"}
          </button>
        </div>

        {/* Report output */}
        <div>
          {!result && !loading && (
            <div style={{ background: "rgba(255,255,255,0.04)", border: `0.5px solid ${T.border}`, borderRadius: "12px", padding: "64px 24px", textAlign: "center" }}>
              <FileText size={36} style={{ color: T.w4, margin: "0 auto 12px" }} />
              <p style={{ color: T.w3, fontSize: "13px" }}>Your professional ATI report will appear here</p>
            </div>
          )}

          {loading && (
            <div style={{ background: "rgba(255,255,255,0.04)", border: `0.5px solid ${T.border}`, borderRadius: "12px", padding: "64px 24px", textAlign: "center" }}>
              <MiniGlobe size={40} label="Generating professional ATI report…" color={T.amber} />
            </div>
          )}

          {result && verdict && (
            <div style={{ background: "rgba(255,255,255,0.04)", border: `0.5px solid ${T.borderMd}`, borderRadius: "12px", overflow: "hidden" }}>

              {/* Report header */}
              <div style={{ background: "rgba(255,255,255,0.04)", borderBottom: `0.5px solid ${T.border}`, padding: "20px 22px" }}>
                <div style={{ height: "2px", background: T.amber, margin: "-20px -22px 16px" }} aria-hidden />

                <Label color={T.amber} style={{ marginBottom: "12px" }}>
                  ATI REPORT · Powered by ABOS Aircraft Buy Or Sell
                </Label>

                <div style={{ display: "flex", alignItems: "flex-end", justifyContent: "space-between", gap: "16px" }}>
                  <div>
                    <p style={{ fontSize: "clamp(28px,4vw,36px)", fontWeight: 500, letterSpacing: "-0.04em", lineHeight: 1, color: verdict.color, margin: "0 0 6px" }}>
                      {result.total}<span style={{ fontSize: "14px", color: T.w3, fontWeight: 400 }}>/120</span>
                    </p>
                    <div style={{ display: "flex", alignItems: "center", gap: "8px", flexWrap: "wrap" }}>
                      <span style={{
                        fontSize: "9px", fontWeight: 700, letterSpacing: "0.08em", textTransform: "uppercase",
                        padding: "3px 10px", borderRadius: "99px", background: verdict.bg,
                        border: `0.5px solid ${verdict.bdr}`, color: verdict.color,
                      }}>
                        {verdict.label}
                      </span>
                      <span style={{ color: T.w3, fontSize: "10px" }}>
                        Deal Score: <span style={{ color: T.w1, fontWeight: 600 }}>{dealScore}/10</span>
                      </span>
                    </div>
                  </div>

                  {reportCode && (
                    <div style={{ textAlign: "right", flexShrink: 0 }}>
                      <Label style={{ marginBottom: "3px" }}>Report Code</Label>
                      <p style={{ fontFamily: "'Courier New', monospace", color: T.amber, fontSize: "11px", fontWeight: 700, letterSpacing: "0.06em", margin: 0 }}>
                        {reportCode}
                      </p>
                    </div>
                  )}
                </div>

                <div style={{ marginTop: "14px", height: "3px", borderRadius: "99px", background: T.w4, overflow: "hidden" }}>
                  <div style={{ height: "100%", width: `${(result.total / 120) * 100}%`, background: verdict.color, borderRadius: "99px", transition: "width 0.5s cubic-bezier(0.16,1,0.3,1)" }} />
                </div>
              </div>

              {/* Aircraft identity */}
              {result.identity_rows?.length > 0 && (
                <div style={{ padding: "16px 22px", borderBottom: `0.5px solid ${T.border}` }}>
                  <Label style={{ marginBottom: "12px" }}>Aircraft Identity</Label>
                  <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", columnGap: "24px" }}>
                    {result.identity_rows.map(r => (
                      <div key={r.label} style={{ display: "flex", justifyContent: "space-between", gap: "8px", padding: "6px 0", borderBottom: `0.5px solid ${T.border}` }}>
                        <span style={{ fontSize: "10px", color: T.w3, flexShrink: 0 }}>{r.label}</span>
                        <span style={{ fontSize: "10px", color: T.w1, fontWeight: 600, textAlign: "right", overflow: "hidden", textOverflow: "ellipsis", whiteSpace: "nowrap" }}>{r.value}</span>
                      </div>
                    ))}
                  </div>
                </div>
              )}

              {/* Valuation */}
              {omvmMid && (
                <div style={{ padding: "16px 22px", borderBottom: `0.5px solid ${T.border}`, display: "grid", gridTemplateColumns: "1fr 1fr 1fr", gap: "16px" }}>
                  <div>
                    <Label style={{ marginBottom: "4px" }}>OMVM Range</Label>
                    <p style={{ fontSize: "11px", fontWeight: 600, color: T.w2, margin: 0 }}>
                      ${result.omvm_low?.toLocaleString()} – ${result.omvm_high?.toLocaleString()}
                    </p>
                  </div>
                  <div>
                    <Label style={{ marginBottom: "4px" }}>Midpoint</Label>
                    <p style={{ fontSize: "13px", fontWeight: 600, color: T.w1, margin: 0 }}>${omvmMid.toLocaleString()}</p>
                  </div>
                  <div>
                    <Label style={{ marginBottom: "4px" }}>vs Market</Label>
                    {priceDiff ? (
                      <p style={{ fontSize: "13px", fontWeight: 700, color: parseFloat(priceDiff) >= 0 ? T.teal : T.red, margin: 0 }}>
                        {parseFloat(priceDiff) >= 0 ? "▼" : "▲"} {Math.abs(parseFloat(priceDiff))}%
                      </p>
                    ) : <p style={{ fontSize: "13px", color: T.w3, margin: 0 }}>—</p>}
                  </div>
                  {/* AI Transparency Notice — EU AI Act Art. 50 */}
                  <div style={{
                    gridColumn: "1 / -1",
                    marginTop: "16px",
                    padding: "12px 16px",
                    background: "rgba(245,194,66,0.04)",
                    border: "0.5px solid rgba(245,194,66,0.18)",
                    borderRadius: "8px",
                    display: "flex",
                    gap: "10px",
                    alignItems: "flex-start",
                  }}>
                    <span style={{ fontSize: "13px", lineHeight: 1, flexShrink: 0, marginTop: "1px" }}>⚠️</span>
                    <p style={{ fontSize: "11px", color: "rgba(255,255,255,0.45)", lineHeight: 1.65, margin: 0 }}>
                      <strong style={{ color: "rgba(245,194,66,0.75)", fontWeight: 700 }}>AI notice:</strong>{" "}
                      The ATI Score and OMVM valuation estimate are generated using artificial intelligence tools based on available data (FAA registry, NTSB database, market comparables). These outputs are for informational purposes only and do not replace a professional technical inspection or formal appraisal. Any final purchase or sale decision should include an independent pre-buy inspection.{" "}
                      <a href="/legal/ai-transparency" style={{ color: "rgba(245,194,66,0.55)", textDecoration: "none" }}>
                        Full AI disclosure (EU AI Act Art. 50) →
                      </a>
                    </p>
                  </div>
                </div>
              )}

              {/* Dimension scores */}
              <div style={{ padding: "16px 22px", borderBottom: `0.5px solid ${T.border}` }}>
                <Label style={{ marginBottom: "14px" }}>Dimension Scores · 15 pts each</Label>
                {DIMS.map(d => (
                  <DimRow key={d.key} label={d.label} score={result[d.key] || 0} reason={result.reasons?.[d.key]} />
                ))}
              </div>

              {/* Executive summary */}
              <div style={{ padding: "16px 22px", borderBottom: `0.5px solid ${T.border}` }}>
                <Label style={{ marginBottom: "8px" }}>Executive Summary</Label>
                <p style={{ fontSize: "13px", color: T.w2, lineHeight: 1.7, margin: 0 }}>{result.summary}</p>
              </div>

              {/* Strengths / Risks */}
              <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", borderBottom: `0.5px solid ${T.border}` }}>
                <div style={{ padding: "16px 22px", borderRight: `0.5px solid ${T.border}` }}>
                  <Label color={T.teal} style={{ marginBottom: "10px" }}>Key Strengths</Label>
                  <BulletList items={result.strengths} color={T.teal} />
                </div>
                <div style={{ padding: "16px 22px" }}>
                  <Label color={T.red} style={{ marginBottom: "10px" }}>Risk Factors</Label>
                  <BulletList items={result.risks} color={T.red} />
                </div>
              </div>

              {/* Recommendations */}
              <div style={{ padding: "16px 22px", borderBottom: `0.5px solid ${T.border}` }}>
                <Label color={T.amber} style={{ marginBottom: "10px" }}>Recommendations</Label>
                <BulletList items={result.recommendations} color={T.amber} />
              </div>

              {/* Export footer */}
              <div style={{ padding: "14px 22px", display: "flex", alignItems: "center", justifyContent: "space-between", gap: "12px" }}>
                <p style={{ fontFamily: "'Courier New', monospace", fontSize: "10px", color: T.w3, letterSpacing: "0.04em", margin: 0 }}>
                  {reportCode}
                </p>
                <button
                  onClick={() => exportDocx(result, reportCode)}
                  style={{
                    display: "inline-flex", alignItems: "center", gap: "7px", padding: "9px 18px",
                    borderRadius: "8px", background: T.amberDim, border: `0.5px solid ${T.amberBdr}`,
                    color: T.amber, fontWeight: 600, fontSize: "11px", cursor: "pointer", transition: "background 0.15s",
                  }}
                  onMouseEnter={(e) => { e.currentTarget.style.background = "rgba(245,194,66,0.14)"; }}
                  onMouseLeave={(e) => { e.currentTarget.style.background = T.amberDim; }}
                >
                  <Download size={14} />
                  Export .docx
                </button>
              </div>
            </div>
          )}
        </div>
      </div>
    </div>
  );
}