import { useState } from "react";
import { Link } from "react-router-dom";
import { Database, FileText, RotateCw, ShieldCheck, TrendingUp, Zap } from "lucide-react";
import { orchestrateATIScoring } from "@/api/orchestrateATIScoring";
import { base44 } from "@/api/base44Client";
import { lookupAircraft } from "@/lib/aircraftLookup";
import { extractAircraftSpecs, mergeExtractedSpecs } from "@/lib/aircraftInput";
import { saveReport, recordUsage } from "@/lib/entitlements";
import { useEntitlementGate } from "@/hooks/useEntitlementGate";
import QuickScoreLookupForm from "@/components/ati/QuickScoreLookupForm";
import AircraftMinimumFields from "@/components/ati/AircraftMinimumFields";
import AircraftExtraInput from "@/components/aircraft-input/AircraftExtraInput";
import MiniGlobe from "@/components/MiniGlobe";
import EntitlementGateModal from "@/components/monetization/EntitlementGateModal";
import OutputScoreGauge from "@/components/output/OutputScoreGauge";
import OutputDimensionRow from "@/components/output/OutputDimensionRow";
import OutputBriefNarrative from "@/components/output/OutputBriefNarrative";
import OutputAINotice from "@/components/output/OutputAINotice";

const DIMS=[["documentation","Documentation"],["technical","Technical"],["transparency","Transparency"],["transaction_ready","Transaction ready"],["usage_mission","Usage / mission"],["storage_exposure","Storage / exposure"],["config_clarity","Configuration clarity"],["market_readiness","Market readiness"]];
const readParam=k=>new URLSearchParams(window.location.search).get(k)||"";
const emptyDetails=()=>({year:"",make:"",model:"",engine_model:"",total_time:"",engine_hours:"",tbo:"",asking_price:""});
const initialDetails=()=>({year:readParam("year"),make:readParam("make"),model:readParam("model"),engine_model:readParam("engine_model"),total_time:readParam("total_time"),engine_hours:readParam("engine_hours"),tbo:readParam("tbo"),asking_price:readParam("asking_price")});
const totalOf=r=>DIMS.reduce((sum,[key])=>sum+(r?.[key]||0),0);
const verdictOf=n=>n>=96?"Strong buy":n>=80?"Buy":n>=60?"Review — due diligence":"Caution — investigate";
function Upgrade({to,icon:Icon,title,text}){return <Link to={to} className="output-outline-button w-full justify-start"><Icon className="h-4 w-4 text-[var(--brand-primary)]"/><span className="text-left"><strong className="block text-sm">{title}</strong><small className="output-muted block font-normal">{text}</small></span></Link>}

export default function ATIQuickScore(){
 const {gate,requireAccess,closeGate,startCheckout}=useEntitlementGate();
 const [input,setInput]=useState(()=>readParam("aircraft_data")),[nReg,setNReg]=useState(()=>readParam("registration")),[details,setDetails]=useState(initialDetails),[lookupStatus,setLookupStatus]=useState(()=>readParam("registration")&&readParam("year")&&readParam("make")&&readParam("model")?"found":"idle"),[lookupLoading,setLookupLoading]=useState(false),[lookupError,setLookupError]=useState(""),[scorePayload,setScorePayload]=useState(""),[submitted,setSubmitted]=useState(false),[loading,setLoading]=useState(false),[files,setFiles]=useState([]),[autoFilling,setAutoFilling]=useState(false),[result,setResult]=useState(null),[error,setError]=useState("");
 const buildInput=()=>[[details.year,details.make,details.model].filter(Boolean).join(" "),nReg&&`Registration: ${nReg}`,details.engine_model&&`Engine: ${details.engine_model}`,details.total_time&&`Airframe Total Time: ${details.total_time} hrs`,details.engine_hours&&`Engine SMOH: ${details.engine_hours} hrs`,details.tbo&&`TBO: ${details.tbo} hrs`,details.asking_price&&`Asking Price: $${details.asking_price}`,input.trim()&&`Listing text:\n${input.trim()}`].filter(Boolean).join("\n");
 async function lookup(){const reg=nReg.trim().toUpperCase().replace(/[^A-Z0-9]/g,"");if(!/^N[0-9A-Z]{1,6}$/.test(reg)){setLookupError("Enter a valid N-Number, for example N12345.");return}setNReg(reg);setLookupLoading(true);setLookupError("");try{const data=await lookupAircraft(reg);if(!data?.found){setDetails(emptyDetails());setLookupStatus("not_found")}else{const a=data.aircraft||{},l=data.listing||{};setDetails(c=>({year:a.year||a.year_mfr||c.year,make:a.make||c.make,model:a.model||c.model,engine_model:l.engine_model||a.engine_model||c.engine_model,total_time:l.total_time||a.total_time||c.total_time,engine_hours:l.engine_hours||a.engine_hours||c.engine_hours,tbo:l.tbo||a.tbo||c.tbo,asking_price:l.asking_price||c.asking_price}));setLookupStatus("found")}}catch(e){setLookupError(e?.response?.data?.error||"Lookup failed. Check the N-Number and try again.");setLookupStatus("error")}finally{setLookupLoading(false)}}
 async function autoFill(){if(!input.trim()&&!files.length)return;setAutoFilling(true);try{const uploaded=await Promise.all(files.map(file=>base44.integrations.Core.UploadFile({file})));const urls=uploaded.map(x=>(x?.data??x)?.file_url).filter(Boolean);const extracted=await extractAircraftSpecs({listingText:input.trim(),fileUrls:urls});setDetails(c=>({...c,...mergeExtractedSpecs(c,extracted).merged}))}catch(e){setError(e.message||"Auto-fill failed.")}finally{setAutoFilling(false)}}
 async function score(){if(!details.make?.trim()||!details.model?.trim()||loading)return;const detected=buildInput().match(/N\d{1,6}[A-Z]{0,2}/i)?.[0]?.toUpperCase()||"";const reg=(nReg||detected).toUpperCase();if(!(await requireAccess("ATI_SCORE",reg)))return;const payload=buildInput();setScorePayload(payload);setLoading(true);setError("");setResult(null);setSubmitted(true);try{const res=await orchestrateATIScoring({input:payload,nReg:reg});setResult(res);try{await saveReport({product_key:"ATI_SCORE",aircraft_registration:reg,aircraft_label:[details.year,details.make,details.model].filter(Boolean).join(" "),report_type:"ati_score",result_data:res,confidence:res?.data_confidence||"unverified"});await recordUsage({product_key:"ATI_SCORE",aircraft_registration:reg})}catch(_){}}catch(e){if([401,403].includes(e?.response?.status||e?.status)){base44.auth.redirectToLogin(window.location.href);return}setError(e?.response?.data?.error||e.message||"Scoring failed. Please try again.")}finally{setLoading(false)}}
 const reset=()=>{setSubmitted(false);setResult(null);setError("");setInput("");setNReg("");setDetails(emptyDetails());setLookupStatus("idle");setLookupError("");setScorePayload("")};
 const total=totalOf(result),mid=result?.omvm_low&&result?.omvm_high?Math.round((result.omvm_low+result.omvm_high)/2):null;const reportParams=new URLSearchParams({registration:nReg,aircraft_data:scorePayload||buildInput()});
 return <div className="output-shell px-4 py-10"><main className="mx-auto max-w-3xl"><header className="mb-8 text-center"><span className="inline-flex items-center gap-2 rounded-full border border-[var(--brand-primary)]/20 bg-[var(--brand-primary)]/5 px-3 py-1.5 text-[10px] font-black uppercase text-[var(--brand-primary)]"><Database className="h-3.5 w-3.5"/>FAA registry · Free estimate</span><h1 className="mt-4 text-4xl font-bold">FAA Check & <span className="text-[var(--brand-primary)]">Free Valuation</span></h1><p className="output-muted mx-auto mt-3 max-w-xl text-sm">Verify a U.S. N-Number and receive an eight-dimension aircraft intelligence score.</p></header>
 {!submitted&&<section className="output-panel p-5 sm:p-6"><div className="space-y-7"><QuickScoreLookupForm value={nReg} onChange={v=>{setNReg(v);setDetails(emptyDetails());setLookupStatus("idle");setLookupError("")}} onLookup={lookup} loading={lookupLoading} error={lookupError}/>{["found","not_found"].includes(lookupStatus)&&<><AircraftMinimumFields details={details} onChange={(k,v)=>setDetails(c=>({...c,[k]:v}))} status={lookupStatus}/><AircraftExtraInput listingText={input} onListingTextChange={setInput} files={files} onFilesChange={setFiles} onAutoFill={autoFill} autoFilling={autoFilling}/>{error&&<p className="rounded-lg border border-red-500/30 bg-red-500/10 p-3 text-sm text-red-400">{error}</p>}<button onClick={score} disabled={!details.make?.trim()||!details.model?.trim()||loading} className="output-primary-button w-full"><Zap className="h-4 w-4"/>Get Free Aircraft Valuation</button></>}</div></section>}
 {submitted&&loading&&<section className="output-panel py-16 text-center"><MiniGlobe size={44} label="Running ATI analysis…" color="#E0B034"/></section>}
 {submitted&&!loading&&<div className="space-y-4">{result&&<><OutputScoreGauge score={total} max={120} label="ATI aircraft score" verdict={verdictOf(total)}><div className="mt-3 flex flex-wrap justify-center gap-4 text-xs sm:justify-start">{nReg&&<span className="output-metric output-muted">{nReg}</span>}{mid&&<span><span className="output-muted">Market value </span><strong className="output-metric text-[var(--brand-success)]">${mid.toLocaleString()}</strong></span>}</div></OutputScoreGauge><section className="output-panel p-5"><h2 className="mb-3 text-lg font-bold">Eight-dimension breakdown</h2>{DIMS.map(([key,label])=><OutputDimensionRow key={key} label={label} score={result[key]||0}/>)}</section>{(result.flash_line||(result.asking_price&&result.omvm_low))&&<OutputBriefNarrative title="Review flags" risks={[result.flash_line||`Asking price $${result.asking_price.toLocaleString()} compared with OMVM $${result.omvm_low.toLocaleString()}–$${result.omvm_high.toLocaleString()}.`]}/>}<OutputAINotice/><section className="output-panel p-5"><p className="mb-3 text-[10px] font-bold uppercase text-[var(--brand-primary)]">Continue your analysis</p><div className="grid gap-2"><Upgrade to={`/ati-full-report?${reportParams}`} icon={FileText} title="Full ATI Report" text="Executive summary, risks and downloadable report"/><Upgrade to="/valuation-studio" icon={TrendingUp} title="OMVM Price Check" text="Market-calibrated valuation with comparables"/><Upgrade to="/ati-verify" icon={ShieldCheck} title="ATI PASS Verify" text="Independent document verification"/></div></section></>}{error&&<p className="output-panel border-red-500/30 p-4 text-red-400">{error}</p>}<button onClick={reset} className="output-outline-button mx-auto"><RotateCw className="h-4 w-4"/>Score another aircraft</button></div>}
 </main><EntitlementGateModal gate={gate} onClose={closeGate} onCheckout={startCheckout}/></div>;
}