import { useState } from "react";
import { useNavigate } from "react-router-dom";
import { base44 } from "@/api/base44Client";
import BuyerOnboardingForm from "@/components/buy/BuyerOnboardingForm";
import BuyerIntentConnector from "@/components/buy/BuyerIntentConnector";

export default function BuyPipeline() {
  const [loading, setLoading] = useState(false); const [active, setActive] = useState(null); const navigate = useNavigate();
  const start = async (answers) => { setLoading(true); const response = await base44.functions.invoke("startBuyerTrial", answers); setActive(response.data); setLoading(false); };
  return <main className="min-h-screen bg-background px-5 py-10 md:px-10"><div className="mx-auto max-w-5xl"><p className="font-mono text-xs uppercase tracking-[.2em] text-accent">BUY PIPELINE · Intelligence workspace</p><h1 className="mt-3 text-balance text-4xl font-black tracking-tight md:text-6xl">Rozhoduj se rychle. Rozhoduj se s jistotou.</h1><p className="mt-4 max-w-2xl text-lg leading-8 text-muted-foreground">Market research, comparables, pricing, due diligence a kalkulace — 3 dny bez karty.</p>{!active ? <div className="mt-10 grid gap-6 md:grid-cols-[1fr_.8fr]"><section className="rounded-2xl border border-border bg-card p-6"><h2 className="text-xl font-bold">Nastav svůj buyer brief</h2><p className="mt-2 text-sm text-muted-foreground">3 odpovědi a otevřeme všechny BUY nástroje.</p><div className="mt-6"><BuyerOnboardingForm onSubmit={start} loading={loading} /></div></section><aside className="rounded-2xl border border-accent/30 bg-accent/10 p-6"><p className="font-mono text-xs text-accent">ALL ACCESS</p><ul className="mt-4 space-y-3 text-sm"><li>Market search & comparable sales</li><li>ATI Score & FAA lookup</li><li>OMVM, OPEX, leasing & insurance</li><li>Due diligence & Deal Intelligence</li></ul><p className="mt-6 text-sm text-muted-foreground">Potom $199/měsíc nebo <strong className="text-foreground">$999/rok</strong>.</p></aside></div> : <div className="mt-10 space-y-6"><section className="rounded-2xl border border-accent/30 bg-card p-6"><p className="font-mono text-xs uppercase tracking-widest text-accent">Trial activated</p><h2 className="mt-2 text-2xl font-bold">BUY tools jsou otevřené na 3 dny.</h2><p className="mt-2 text-muted-foreground">Tvůj brief je uložený. Začni průzkumem trhu nebo připoj externí inzerát.</p><button type="button" onClick={() => navigate("/listings")} className="mt-5 rounded-lg bg-accent px-4 py-3 font-semibold text-accent-foreground">Spustit market search</button></section><BuyerIntentConnector /></div>}</div></main>;
}