import { useCallback, useState } from "react";
import { Link } from "react-router-dom";
import { Activity, AlertTriangle, Brain, ChevronRight, Gauge, Loader2, Plane, ShieldCheck, TrendingUp, Zap } from "lucide-react";
import { base44 } from "@/api/base44Client";
import InvestmentAssumptions from "@/components/finance/InvestmentAssumptions";
import InvestmentScenarioResults from "@/components/output/InvestmentScenarioResults";
import OutputScoreGauge from "@/components/output/OutputScoreGauge";
import OutputBriefNarrative from "@/components/output/OutputBriefNarrative";
import OutputSkillResultCard from "@/components/output/OutputSkillResultCard";
import OutputAINotice from "@/components/output/OutputAINotice";
const stages=["Digital Twin","OMVM","Engine TBO","OPEX","Insurance","Investment Brief"];
const healthLabel=n=>n>=70?"Strong opportunity":n>=50?"Moderate interest":"High risk";
export default function InvestmentBrief(){
 const [registration,setRegistration]=useState(""),[annualHours,setAnnualHours]=useState(200),[leaseRevenue,setLeaseRevenue]=useState(0),[jurisdiction,setJurisdiction]=useState("CZ"),[usageType,setUsageType]=useState("rental"),[assumptions,setAssumptions]=useState({purchase_price:0,down_payment_pct:30,interest_rate_pct:7,loan_term_years:10,holding_period_years:5,residual_value_pct:85,downtime_days:20,maintenance_reserve_annual:0,transaction_costs:0,vat_status:"unknown",ownership_structure:"individual"}),[loading,setLoading]=useState(false),[result,setResult]=useState(null),[error,setError]=useState(null),[paymentRequired,setPaymentRequired]=useState(false);
 const runAnalysis=useCallback(async()=>{if(!registration.trim())return;setLoading(true);setError(null);setPaymentRequired(false);setResult(null);try{const response=await base44.functions.invoke("invokeSkill",{skill_id:"abos.skill.investment_health.v1",inputs:{registration:registration.trim().toUpperCase(),annual_hours:annualHours,lease_revenue:leaseRevenue,jurisdiction,usage_type:usageType,...assumptions}});setResult(response.data)}catch(e){const required=e?.response?.status===402||e?.response?.data?.error==="payment_required";setPaymentRequired(required);setError(required?"Investment analysis is not unlocked for this aircraft.":(e.message||"Failed to run investment analysis"))}finally{setLoading(false)}},[registration,annualHours,leaseRevenue,jurisdiction,usageType,assumptions]);
 const data=result?.result||{},twin=data.twin_context,skills=data.skill_results||{},scenarioAssumptions={...assumptions,annual_hours:annualHours,lease_revenue:leaseRevenue};
 return <div className="output-shell px-4 py-10"><main className="mx-auto max-w-6xl"><header><p className="text-[10px] font-black uppercase text-[var(--brand-primary)]">Aviation Investment OS</p><h1 className="mt-2 flex items-center gap-2 text-4xl font-bold"><Brain className="h-8 w-8 text-[var(--brand-primary)]"/>Aircraft Investment Advisor</h1><p className="output-muted mt-3 max-w-2xl text-sm">Evidence-grounded ownership scenarios, operating economics and investment sensitivity.</p></header><div className="output-panel mt-6 overflow-x-auto p-4"><div className="flex min-w-max items-center gap-2">{stages.map((stage,i)=><div key={stage} className="flex items-center gap-2"><span className="rounded-full border border-[var(--brand-border)] px-3 py-2 text-xs font-semibold">{stage}</span>{i<stages.length-1&&<span className="text-[var(--brand-primary)]">→</span>}</div>)}</div></div><div className="output-panel mt-4 flex flex-col justify-between gap-3 p-4 sm:flex-row sm:items-center"><div><p className="font-bold">Ask the Aircraft Investment Advisor</p><p className="output-muted text-xs">Use free-form chat for follow-up questions and scenario interpretation.</p></div><Link to="/finance-advisor" className="output-primary-button"><ChevronRight className="h-4 w-4"/>Open chat</Link></div>
 <section className="output-panel mt-6 p-5"><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><label><span className="output-muted mb-1 block text-xs">Registration</span><input value={registration} onChange={e=>setRegistration(e.target.value.toUpperCase())} onKeyDown={e=>e.key==='Enter'&&!loading&&runAnalysis()} placeholder="N12345" className="output-input output-metric"/></label><label><span className="output-muted mb-1 block text-xs">Annual hours</span><input type="number" value={annualHours} onChange={e=>setAnnualHours(+e.target.value)} className="output-input"/></label><label><span className="output-muted mb-1 block text-xs">Lease revenue / year</span><input type="number" value={leaseRevenue} onChange={e=>setLeaseRevenue(+e.target.value)} className="output-input"/></label><label><span className="output-muted mb-1 block text-xs">Jurisdiction</span><select value={jurisdiction} onChange={e=>setJurisdiction(e.target.value)} className="output-input"><option value="CZ">Czech Republic</option><option value="US">United States</option><option value="EU">EU (generic)</option></select></label></div><div className="mt-5 [&_input]:output-input [&_select]:output-input [&_legend]:text-[var(--brand-text)] [&_span]:output-muted"><InvestmentAssumptions value={assumptions} onChange={setAssumptions}/></div><div className="mt-4 flex flex-col gap-3 sm:flex-row sm:items-end"><label><span className="output-muted mb-1 block text-xs">Usage type</span><select value={usageType} onChange={e=>setUsageType(e.target.value)} className="output-input"><option value="rental">Rental</option><option value="school">Flight school</option><option value="business">Business</option><option value="private">Private</option></select></label><button onClick={runAnalysis} disabled={loading||!registration.trim()} className="output-primary-button sm:ml-auto">{loading?<Loader2 className="h-4 w-4 animate-spin"/>:<Brain className="h-4 w-4"/>}{loading?"Analyzing…":"Run analysis"}</button></div></section>
 {loading&&<div className="output-panel mt-5 flex items-center gap-3 p-4"><Loader2 className="h-5 w-5 animate-spin text-[var(--brand-primary)]"/><div><p className="font-bold">Running deterministic valuation and ownership scenarios</p><p className="output-muted text-xs">The completed skills will appear with their evidence.</p></div></div>}{error&&<div className="mt-5 flex gap-3 rounded-lg border border-red-500/30 bg-red-500/10 p-4"><AlertTriangle className="h-5 w-5 shrink-0 text-red-400"/><div><p className="text-sm text-red-400">{error}</p>{paymentRequired&&<Link to="/pricing" className="mt-2 inline-block text-xs font-bold text-[var(--brand-primary)] hover:underline">View investment pricing →</Link>}</div></div>}
 {result&&<div className="mt-6 space-y-5"><OutputScoreGauge score={data.investment_health_score} max={100} label="Investment health score" verdict={`${twin?.registration||registration} — ${healthLabel(data.investment_health_score)}`}><div className="mt-3 flex flex-wrap gap-2 text-xs"><span className="rounded-full bg-[var(--brand-muted)] px-2.5 py-1"><Activity className="mr-1 inline h-3 w-3"/>{data.live_status||"unknown"}</span>{data.deal_radar_eligible&&<span className="rounded-full bg-[var(--brand-primary)]/10 px-2.5 py-1 text-[var(--brand-primary)]"><Zap className="mr-1 inline h-3 w-3"/>Deal Radar eligible</span>}</div></OutputScoreGauge>{twin&&<section className="grid grid-cols-2 gap-3 lg:grid-cols-4">{[["ATI score",twin.ati_total?`${twin.ati_total}/120`:"N/A",ShieldCheck],["OMVM value",twin.omvm_value?`$${twin.omvm_value.toLocaleString()}`:"N/A",TrendingUp],["Engine remaining",twin.engine_remaining_pct!=null?`${twin.engine_remaining_pct}%`:"N/A",Gauge],["Deal label",twin.deal_label||"N/A",Plane]].map(([label,value,Icon])=><article key={label} className="output-panel p-4"><Icon className="h-4 w-4 text-[var(--brand-primary)]"/><p className="output-muted mt-2 text-[10px] uppercase">{label}</p><p className="output-metric mt-1 font-bold">{value}</p></article>)}</section>}<InvestmentScenarioResults scenarios={data.financial_scenarios} assumptions={scenarioAssumptions}/><OutputBriefNarrative brief={data.ai_brief} title="AI investment brief"/><section><p className="mb-3 text-[10px] font-bold uppercase text-[var(--brand-primary)]">Completed analysis skills</p><div className="grid gap-3 lg:grid-cols-2">{Object.entries(skills).map(([id,response])=><OutputSkillResultCard key={id} skillId={id} response={response}/>)}</div></section><OutputAINotice>Investment scenarios combine deterministic calculations with AI-assisted synthesis. Validate assumptions with qualified aviation, finance, tax and legal professionals.</OutputAINotice><div className="flex flex-wrap gap-3"><Link to={`/twin/${twin?.registration}`} className="output-outline-button"><Plane className="h-4 w-4"/>Digital Twin</Link><Link to="/opex-calculator" className="output-outline-button"><Activity className="h-4 w-4"/>OPEX Calculator</Link></div></div>}
 </main></div>;
}