import { useState } from "react";
import { base44 } from "@/api/base44Client";
import SellerIntakeForm from "@/components/sell/SellerIntakeForm";
import FinderFeeTable from "@/components/sell/FinderFeeTable";

export default function SellPipeline() {
  const [loading, setLoading] = useState(false); const [report, setReport] = useState(null); const [price, setPrice] = useState("");
  const create = async (form) => { setLoading(true); setPrice(form.asking_price); const response = await base44.functions.invoke("createSellerListing", form); setReport(response.data); setLoading(false); };
  return <main className="min-h-screen bg-background px-5 py-10 md:px-10"><div className="mx-auto max-w-5xl"><p className="font-mono text-xs uppercase tracking-[.2em] text-gold">SELL PIPELINE · Readiness workspace</p><h1 className="mt-3 text-balance text-4xl font-black tracking-tight md:text-6xl">Připrav asset. Prodej s důvěrou.</h1><p className="mt-4 max-w-2xl text-lg leading-8 text-muted-foreground">První letadlo je zdarma — data, readiness report, listing i leads. Další jsou success-only.</p><div className="mt-10 grid gap-6 lg:grid-cols-[1fr_.9fr]"><section className="rounded-2xl border border-border bg-card p-6"><h2 className="text-xl font-bold">Zadej letadlo</h2><p className="mt-2 text-sm text-muted-foreground">Použij N-number, nebo vyplň základní parametry ručně.</p><div className="mt-6"><SellerIntakeForm onSubmit={create} loading={loading} /></div></section><FinderFeeTable askingPrice={price} /></div>{report && <section className="mt-6 rounded-2xl border border-primary/30 bg-primary/10 p-6"><p className="font-mono text-xs uppercase tracking-widest text-gold">Listing Readiness Report</p><h2 className="mt-2 text-2xl font-bold">{report.listing?.year} {report.listing?.make} {report.listing?.model}</h2><div className="mt-5 grid gap-3 sm:grid-cols-3"><div className="rounded-lg bg-card p-4"><p className="text-xs text-muted-foreground">ATI Score</p><p className="mt-1 text-2xl font-bold">{report.listing?.ati_score ?? "—"}</p></div><div className="rounded-lg bg-card p-4"><p className="text-xs text-muted-foreground">OMVM Value</p><p className="mt-1 text-2xl font-bold">{report.listing?.omvm_value ? `$${Number(report.listing.omvm_value).toLocaleString()}` : "Queued"}</p></div><div className="rounded-lg bg-card p-4"><p className="text-xs text-muted-foreground">Listing</p><p className="mt-1 text-2xl font-bold">Ready</p></div></div><p className="mt-5 text-sm text-muted-foreground">{report.freeListing ? "Toto je tvůj první listing — bez finders fee." : `Při close přes ABOS escrow bude fee ${report.findersFee.percent}% (${Number(report.findersFee.fee).toLocaleString()} USD).`}</p></section>}</div></main>;
}