/**
 * TermsOfService.jsx — ABOS Marketspace
 * DS v3 styling — ink system, amber accents
 */
import { useState } from "react";
import { useNavigate } from "react-router-dom";
import { ChevronDown, ChevronRight, ArrowLeft, FileText } from "lucide-react";

const C = {
  ink:  "#04060a", ink1: "#0d1117", ink2: "#111620", ink3: "#1a2235",
  amber: "#f5c242", amberDim: "rgba(245,194,66,0.09)", amberBorder: "rgba(245,194,66,0.22)",
  teal: "#5dcaa5", tealDim: "rgba(93,202,165,0.09)", tealBorder: "rgba(93,202,165,0.20)",
  w1: "rgba(255,255,255,0.90)", w2: "rgba(255,255,255,0.60)",
  w3: "rgba(255,255,255,0.35)", border: "rgba(255,255,255,0.08)",
};

const SECTIONS = [
  {
    id: "1", title: "1. Acceptance of Terms",
    content: `By accessing or using ABOS Marketspace ("Platform", "Service") operated by ABOS s.r.o. ("we", "us", "our"), you agree to be bound by these Terms of Service ("Terms"). If you do not agree, do not use the Platform.

These Terms apply to all users including free users (Free Explorer), paid subscribers (Starter, Pro, Enterprise), and visitors accessing any publicly available part of the Platform.`
  },
  {
    id: "2", title: "2. Platform Description",
    content: `ABOS Marketspace is an aviation transparency and market intelligence platform providing:
• Aircraft listing discovery and market data
• ATI (Aircraft Transparency Index) scoring and analysis
• OMVM (Off-Market Valuation Model) estimates
• Aircraft ownership and registration verification
• Document and compliance status checks

The Platform is intended for licensed aviation professionals, aircraft buyers/sellers, dealers, and brokers. Users must be at least 18 years of age.`
  },
  {
    id: "3", title: "3. ATI Score & OMVM — AI Disclaimer",
    content: `IMPORTANT — PLEASE READ CAREFULLY:

The ATI Score, OMVM (Off-Market Valuation Model), and all related outputs are generated by artificial intelligence systems and are provided for informational and decision-support purposes ONLY.

These outputs:
• Are NOT a certified aircraft appraisal under any regulatory standard
• Are NOT a substitute for a professional pre-purchase inspection (PPI)
• Are NOT a guarantee of market value, airworthiness, or title
• May contain errors, omissions, or outdated information
• Should NOT be used as the sole basis for any purchase, sale, or financing decision

ABOS expressly disclaims all liability for any losses, damages, or decisions made in reliance on ATI Score or OMVM outputs. Always obtain a professional inspection and independent appraisal before any aviation transaction.

In accordance with EU AI Act 2024/1689, users are informed that this system uses automated decision-support tools. Final decisions remain solely with the human user.`
  },
  {
    id: "4", title: "4. User Accounts & Tiers",
    content: `4.1 Registration. You must provide accurate, complete information and keep it updated.

4.2 Tier Plans. The Platform offers Free Explorer, Starter (€29/month), Pro (€99/month), and Enterprise (€249/month) plans. Features vary by tier as described on the Pricing page.

4.3 Account Security. You are responsible for maintaining confidentiality of your credentials. Notify us immediately of any unauthorized access.

4.4 Prohibited Use. You may not:
• Use the Platform for illegal activities or to circumvent regulations
• Scrape, crawl, or systematically extract Platform data
• Share account credentials with third parties
• Submit false or misleading aircraft listings or valuation inputs
• Attempt to reverse-engineer or circumvent the ATI scoring system`
  },
  {
    id: "5", title: "5. Payments & Subscriptions",
    content: `5.1 Billing. Subscription fees are billed monthly or annually in advance. All prices are exclusive of VAT where applicable.

5.2 Cancellation. You may cancel your subscription at any time. Access continues until the end of the current billing period. No refunds for partial periods.

5.3 One-Time Fees. Certain services (e.g., ATI PASS verification packages) may carry one-time fees. These are non-refundable once the service has been delivered.

5.4 Price Changes. We reserve the right to change subscription prices with 30 days written notice.

5.5 Affiliate Program. Participants in the ABOS Affiliate Program are subject to separate Affiliate Terms and earn commissions as specified in the current Commission Schedule.`
  },
  {
    id: "6", title: "6. Intellectual Property",
    content: `6.1 Platform IP. The Platform, ATI methodology, OMVM model, WIZARD engine, all scoring algorithms, and brand assets (ABOS, IntraZone, ATI PASS) are proprietary to ABOS s.r.o. and protected by copyright, trademark, and trade secret law.

6.2 User Content. You retain ownership of content you submit. By submitting, you grant ABOS a non-exclusive, worldwide license to use, process, and display such content to operate the Platform.

6.3 FAA Data. Aircraft registration data sourced from the FAA Aviation Data Systems Branch is public domain. ABOS's processing, scoring, and enrichment of this data is proprietary.

6.4 Feedback. Any suggestions or feedback you provide may be used by ABOS without compensation or attribution.`
  },
  {
    id: "7", title: "7. Data Protection & Privacy",
    content: `Your use of the Platform is also governed by our Privacy Policy, incorporated herein by reference.

7.1 GDPR. For users in the European Economic Area, we process personal data in accordance with GDPR (Regulation 2016/679). Our legal bases include contract performance, legitimate interests, and consent where required.

7.2 Data Retention. User behavioral data is automatically deleted after 90 days. Account data is retained for the duration of your account plus statutory periods required by law.

7.3 Your Rights. You have rights to access, rectify, erase, restrict, and port your personal data. Contact: privacy@abos-marketspace.com`
  },
  {
    id: "8", title: "8. Disclaimers & Limitation of Liability",
    content: `8.1 As-Is. The Platform is provided "as is" and "as available" without warranties of any kind, express or implied.

8.2 Aviation Transactions. Aviation transactions involve significant financial and safety risks. ABOS does not act as a broker, dealer, appraiser, or advisor. All transactions are between the buyer and seller.

8.3 Third-Party Data. We rely on FAA, NTSB, and other third-party data sources which may contain errors or be outdated. We are not responsible for the accuracy of third-party data.

8.4 Liability Cap. To the maximum extent permitted by law, ABOS's total liability shall not exceed the amount paid by you in the 12 months preceding the claim, or €100, whichever is greater.

8.5 Consequential Damages. ABOS is not liable for indirect, incidental, special, consequential, or punitive damages.`
  },
  {
    id: "9", title: "9. Governing Law & Disputes",
    content: `These Terms are governed by the laws of the Czech Republic, without regard to conflict of law principles.

Disputes shall first be attempted to be resolved through good-faith negotiation. If unresolved within 30 days, disputes shall be submitted to the courts of the Czech Republic with jurisdiction in Prague.

For consumers in the EU: You may also use the EU Online Dispute Resolution platform at ec.europa.eu/consumers/odr.`
  },
  {
    id: "10", title: "10. Changes to Terms",
    content: `We may update these Terms at any time. Material changes will be notified via email or in-app notification at least 14 days before taking effect. Continued use after the effective date constitutes acceptance.

Last updated: June 2026 | Version: 1.0`
  },
];

function Section({ section }) {
  const [open, setOpen] = useState(false);
  const isImportant = section.id === "3";

  return (
    <div style={{
      background:    isImportant ? "rgba(245,194,66,0.06)" : "rgba(255,255,255,0.04)",
      border:        `0.5px solid ${isImportant ? C.amberBorder : C.border}`,
      borderRadius:  "12px",
      overflow:      "hidden",
    }}>
      {isImportant && <div style={{ height: "2px", background: C.amber }} />}
      <button
        onClick={() => setOpen(o => !o)}
        style={{
          width:         "100%",
          display:       "flex",
          alignItems:    "center",
          justifyContent:"space-between",
          padding:       "16px 20px",
          background:    "transparent",
          border:        "none",
          cursor:        "pointer",
          textAlign:     "left",
          gap:           "12px",
        }}
      >
        <span style={{ fontSize: "13px", fontWeight: 600, letterSpacing: "-0.02em", color: isImportant ? C.amber : C.w1 }}>
          {section.title}
          {isImportant && (
            <span style={{ marginLeft: "10px", fontSize: "9px", fontWeight: 700, letterSpacing: "0.08em", textTransform: "uppercase", background: C.amberDim, border: `0.5px solid ${C.amberBorder}`, color: C.amber, padding: "2px 8px", borderRadius: "9999px" }}>
              AI NOTICE
            </span>
          )}
        </span>
        {open
          ? <ChevronDown size={14} color={C.w3} />
          : <ChevronRight size={14} color={C.w3} />
        }
      </button>
      {open && (
        <div style={{ padding: "0 20px 20px", borderTop: `0.5px solid ${C.border}` }}>
          <p style={{ fontSize: "13px", color: C.w2, lineHeight: 1.75, whiteSpace: "pre-line", margin: "16px 0 0" }}>
            {section.content}
          </p>
        </div>
      )}
    </div>
  );
}

export default function TermsOfService() {
  const navigate = useNavigate();

  return (
    <div style={{
      background:          C.ink,
      backgroundImage:     "radial-gradient(ellipse at 8% 12%, rgba(245,194,66,0.14) 0%, transparent 52%), radial-gradient(ellipse at 92% 88%, rgba(93,202,165,0.12) 0%, transparent 52%), radial-gradient(ellipse at 85% 8%, rgba(78,142,247,0.07) 0%, transparent 40%), radial-gradient(circle, rgba(255,255,255,0.18) 1px, transparent 1px)",
      backgroundSize:      "100% 100%, 100% 100%, 100% 100%, 24px 24px",
      minHeight:           "100vh",
      fontFamily:          "-apple-system, BlinkMacSystemFont, 'Segoe UI', system-ui, sans-serif",
      color:               C.w1,
    }}>
      <div style={{ position: "fixed", top: "50%", left: "50%", transform: "translate(-50%, -50%) rotate(-8deg)", opacity: 0.055, pointerEvents: "none", zIndex: 0 }}>
        <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 172 106" width="480" height="296">
          <defs>
            <marker id="wm-arr" markerWidth="9" markerHeight="9" refX="8.5" refY="4.5" orient="auto" markerUnits="userSpaceOnUse">
              <polygon points="0,0 9,4.5 0,9" fill="white" />
            </marker>
          </defs>
          <polyline points="2,98 52,8 70,98" stroke="white" strokeWidth="5.5" strokeLinecap="round" strokeLinejoin="round" fill="none" />
          <polyline points="70,98 86,48 102,70 122,14 140,80 156,57" stroke="white" strokeWidth="5.5" strokeLinecap="round" strokeLinejoin="round" fill="none" markerEnd="url(#wm-arr)" />
        </svg>
      </div>

      <div style={{ maxWidth: "760px", margin: "0 auto", padding: "48px 24px 96px", position: "relative", zIndex: 1 }}>

        <button onClick={() => navigate(-1)} style={{ display: "inline-flex", alignItems: "center", gap: "6px", background: "transparent", border: "none", color: C.w3, fontSize: "13px", cursor: "pointer", marginBottom: "32px", padding: 0 }}>
          <ArrowLeft size={14} /> Back
        </button>

        <div style={{ marginBottom: "40px" }}>
          <div style={{ display: "flex", alignItems: "center", gap: "10px", marginBottom: "12px" }}>
            <FileText size={18} color={C.amber} />
            <span style={{ fontSize: "9px", fontWeight: 700, letterSpacing: "0.12em", textTransform: "uppercase", color: C.amber }}>Legal Document</span>
          </div>
          <h1 style={{ fontSize: "clamp(28px,4vw,38px)", fontWeight: 500, letterSpacing: "-0.04em", lineHeight: 1.06, margin: "0 0 12px" }}>
            Terms of Service
          </h1>
          <p style={{ fontSize: "13px", color: C.w2, margin: 0 }}>
            ABOS Marketspace · Last updated June 2026 · Version 1.0
          </p>
          <div style={{ display: "flex", gap: "8px", flexWrap: "wrap", marginTop: "16px" }}>
            {["Czech law applies", "GDPR compliant", "EU AI Act compliant", "Not financial advice"].map(t => (
              <span key={t} style={{ fontSize: "9px", fontWeight: 700, letterSpacing: "0.08em", textTransform: "uppercase", background: C.amberDim, border: `0.5px solid ${C.amberBorder}`, color: C.amber, padding: "2px 10px", borderRadius: "9999px" }}>{t}</span>
            ))}
          </div>
        </div>

        <div style={{ background: "rgba(93,202,165,0.06)", border: `0.5px solid ${C.border}`, borderRadius: "12px", overflow: "hidden", marginBottom: "24px" }}>
          <div style={{ height: "2px", background: C.teal }} />
          <div style={{ padding: "20px 22px" }}>
            <p style={{ fontSize: "13px", color: C.w2, lineHeight: 1.75, margin: 0 }}>
              These Terms of Service govern your use of the ABOS Marketspace platform. Click each section to expand. Section 3 (ATI Score & OMVM Disclaimer) is especially important — please read it before using any scoring or valuation features.
            </p>
          </div>
        </div>

        <div style={{ display: "flex", flexDirection: "column", gap: "8px" }}>
          {SECTIONS.map(s => <Section key={s.id} section={s} />)}
        </div>

        <div style={{ marginTop: "40px", padding: "20px 22px", background: "rgba(255,255,255,0.04)", border: `0.5px solid ${C.border}`, borderRadius: "12px" }}>
          <p style={{ fontSize: "9px", fontWeight: 600, letterSpacing: "0.12em", textTransform: "uppercase", color: C.w3, margin: "0 0 8px" }}>Contact</p>
          <p style={{ fontSize: "13px", color: C.w2, lineHeight: 1.65, margin: 0 }}>
            ABOS s.r.o. · legal@abos-marketspace.com · Prague, Czech Republic<br />
            For privacy requests: privacy@abos-marketspace.com
          </p>
        </div>
      </div>
    </div>
  );
}