import { createClientFromRequest } from 'npm:@base44/sdk@0.8.31';
import { createMimeMessage } from 'npm:mimetext@3.0.24';

Deno.serve(async (req) => {
  try {
    const base44 = createClientFromRequest(req);
    const user = await base44.auth.me();
    if (!user) return Response.json({ error: 'Unauthorized' }, { status: 401 });

    const { action, pipelineId, to, subject, body, docUrl, eventTitle, eventDate, attendeeEmail } = await req.json();

    const pipeline = pipelineId ? await base44.entities.SalesPipeline.get(pipelineId) : null;
    if (pipelineId && !pipeline) return Response.json({ error: 'Pipeline not found' }, { status: 404 });

    // ── Generate purchase agreement in Google Docs ──
    if (action === 'generate_contract') {
      const { accessToken } = await base44.asServiceRole.connectors.getConnection('googledocs');
      const headers = { Authorization: `Bearer ${accessToken}`, 'Content-Type': 'application/json' };

      const reg = pipeline?.registration || 'N/A';
      const title = `Aircraft Purchase Agreement — ${reg} — ${new Date().toISOString().slice(0, 10)}`;

      const createRes = await fetch('https://docs.googleapis.com/v1/documents', {
        method: 'POST', headers, body: JSON.stringify({ title }),
      });
      if (!createRes.ok) {
        const t = await createRes.text();
        return Response.json({ error: `Docs create failed: ${t}` }, { status: 502 });
      }
      const doc = await createRes.json();

      const today = new Date().toLocaleDateString('en-GB', { day: 'numeric', month: 'long', year: 'numeric' });
      const text =
`AIRCRAFT PURCHASE AGREEMENT

Date: ${today}
Prepared via ABOS MarketSpace Sales Pipeline

1. AIRCRAFT
Registration: ${reg}
Description: ${pipeline?.aircraft_label || '—'}
Class: ${(pipeline?.aircraft_class || 'sep').toUpperCase()}

2. PARTIES
Seller: ${user.full_name || user.email}
Buyer: ${pipeline?.buyer_name || '________________________'}
Buyer Email: ${pipeline?.buyer_email || '________________________'}

3. PURCHASE PRICE
Agreed Sale Amount: ${pipeline?.sale_amount ? '$' + Number(pipeline.sale_amount).toLocaleString() : '$________________'}

4. CONDITIONS
- Sale is contingent on a satisfactory pre-buy inspection performed by a certified A&P mechanic.
- Seller warrants that all logbooks and maintenance records provided are complete and accurate.
- Aircraft is sold with a clear title, free of liens and encumbrances.
- Closing shall occur through an escrow arrangement agreed by both parties.

5. SIGNATURES

Seller: ______________________________   Date: ____________

Buyer:  ______________________________   Date: ____________

Generated by ABOS MarketSpace — this draft must be reviewed by qualified legal counsel before execution.
`;

      const updRes = await fetch(`https://docs.googleapis.com/v1/documents/${doc.documentId}:batchUpdate`, {
        method: 'POST', headers,
        body: JSON.stringify({ requests: [{ insertText: { location: { index: 1 }, text } }] }),
      });
      if (!updRes.ok) {
        const t = await updRes.text();
        return Response.json({ error: `Docs update failed: ${t}` }, { status: 502 });
      }

      const url = `https://docs.google.com/document/d/${doc.documentId}/edit`;
      return Response.json({ ok: true, docId: doc.documentId, docUrl: url, title });
    }

    // ── Send email via Gmail ──
    if (action === 'send_email') {
      if (!to) return Response.json({ error: 'Recipient email required' }, { status: 400 });
      const { accessToken } = await base44.asServiceRole.connectors.getConnection('gmail');

      const msg = createMimeMessage();
      msg.setSender({ name: 'ABOS MarketSpace', addr: user.email });
      msg.setRecipient(to);
      msg.setSubject(subject || `Aircraft ${pipeline?.registration || ''} — documents`);
      let fullBody = body || '';
      if (docUrl) fullBody += `\n\nDocument link: ${docUrl}`;
      msg.addMessage({ contentType: 'text/plain', data: fullBody });

      const raw = msg.asEncoded();
      const sendRes = await fetch('https://gmail.googleapis.com/gmail/v1/users/me/messages/send', {
        method: 'POST',
        headers: { Authorization: `Bearer ${accessToken}`, 'Content-Type': 'application/json' },
        body: JSON.stringify({ raw }),
      });
      if (!sendRes.ok) {
        const t = await sendRes.text();
        return Response.json({ error: `Gmail send failed: ${t}` }, { status: 502 });
      }
      const sent = await sendRes.json();
      return Response.json({ ok: true, messageId: sent.id });
    }

    // ── Schedule event in Google Calendar ──
    if (action === 'schedule_event') {
      if (!eventDate) return Response.json({ error: 'Event date required' }, { status: 400 });
      const { accessToken } = await base44.asServiceRole.connectors.getConnection('googlecalendar');

      const start = new Date(eventDate);
      const end = new Date(start.getTime() + 60 * 60 * 1000);
      const event = {
        summary: eventTitle || `${pipeline?.registration || 'Aircraft'} — inspection`,
        description: `Sales Pipeline event for ${pipeline?.aircraft_label || pipeline?.registration || ''} — created via ABOS MarketSpace.`,
        start: { dateTime: start.toISOString() },
        end: { dateTime: end.toISOString() },
        ...(attendeeEmail ? { attendees: [{ email: attendeeEmail }] } : {}),
      };

      const calRes = await fetch('https://www.googleapis.com/calendar/v3/calendars/primary/events?sendUpdates=all', {
        method: 'POST',
        headers: { Authorization: `Bearer ${accessToken}`, 'Content-Type': 'application/json' },
        body: JSON.stringify(event),
      });
      if (!calRes.ok) {
        const t = await calRes.text();
        return Response.json({ error: `Calendar create failed: ${t}` }, { status: 502 });
      }
      const created = await calRes.json();
      return Response.json({ ok: true, eventId: created.id, eventLink: created.htmlLink });
    }

    return Response.json({ error: `Unknown action: ${action}` }, { status: 400 });
  } catch (error) {
    return Response.json({ error: error.message }, { status: 500 });
  }
});