import assert from 'node:assert/strict';
import crypto from 'node:crypto';
import {readFile} from 'node:fs/promises';
import test from 'node:test';
const map=JSON.parse(await readFile(new URL('../entity-domain-map.json',import.meta.url),'utf8'));
const expected=["ATICard","ATICardReview","ATIPassport","ATIVerifyDocument","ATIVerifyScore","ATIVerifySession","AccountDeletion","AdminAuditTrail","AdminDashboard","AdminSettings","AffiliateLink","AircraftAlert","AircraftListing","AirmanReleaseMonitor","ApiKey","ApiRequestLog","AppConfig","AviationNewsItem","AviationService","BillOfSaleDraft","BillingEvent","BrokerAgreement","BrokerAlert","BrokerProfile","CommissionLedger","DealRadar","DealerLead","DealerLocation","DecisionLog","DeveloperAccount","EditorProfile","EngineMaintenance","EngineSpec","EscrowTransaction","ExpertBid","ExpertCrossCheck","ExpertProfile","ExpertValuation","FAAAircraft","FAADocIndex","FeatureRequest","FeatureRollout","FeatureToggle","FeatureUsageMetric","FeatureVote","GlobalRegistry","Lead","LeadEvent","MarketComparable","MarketForecast","MarketReport","NewPlaneBrowser","Order","OwnershipTrace","PartnerConfig","PartnerListingFeed","PermissionLog","PreBuyInspection","ReportRequest","RewardMilestone","SalesFunnel","SalesPipeline","ScraperRun","Settlement","SkillDefinition","StartupProject","SuspensionEvent","TierChange","TokenTransaction","ToolIntegration","ToolInvocation","TrafficAppearance","TrafficSnapshot","User","UserBehavior","UserProfile","VaultDocument","WebhookConfig","Workflow"];
const expectedCounts={"ATICard":47,"ATICardReview":10,"ATIPassport":52,"ATIVerifyDocument":19,"ATIVerifyScore":7,"ATIVerifySession":16,"AccountDeletion":8,"AdminAuditTrail":12,"AdminDashboard":11,"AdminSettings":8,"AffiliateLink":15,"AircraftAlert":13,"AircraftListing":23,"AirmanReleaseMonitor":8,"ApiKey":14,"ApiRequestLog":7,"AppConfig":3,"AviationNewsItem":8,"AviationService":26,"BillOfSaleDraft":37,"BillingEvent":14,"BrokerAgreement":21,"BrokerAlert":18,"BrokerProfile":14,"CommissionLedger":20,"DealRadar":7,"DealerLead":10,"DealerLocation":15,"DecisionLog":11,"DeveloperAccount":17,"EditorProfile":18,"EngineMaintenance":19,"EngineSpec":15,"EscrowTransaction":33,"ExpertBid":12,"ExpertCrossCheck":15,"ExpertProfile":22,"ExpertValuation":12,"FAAAircraft":25,"FAADocIndex":8,"FeatureRequest":9,"FeatureRollout":14,"FeatureToggle":13,"FeatureUsageMetric":12,"FeatureVote":3,"GlobalRegistry":15,"Lead":11,"LeadEvent":13,"MarketComparable":13,"MarketForecast":39,"MarketReport":46,"NewPlaneBrowser":10,"Order":9,"OwnershipTrace":13,"PartnerConfig":18,"PartnerListingFeed":13,"PermissionLog":11,"PreBuyInspection":81,"ReportRequest":8,"RewardMilestone":8,"SalesFunnel":20,"SalesPipeline":26,"ScraperRun":10,"Settlement":14,"SkillDefinition":19,"StartupProject":19,"SuspensionEvent":16,"TierChange":15,"TokenTransaction":10,"ToolIntegration":17,"ToolInvocation":15,"TrafficAppearance":18,"TrafficSnapshot":9,"User":14,"UserBehavior":17,"UserProfile":16,"VaultDocument":24,"WebhookConfig":10,"Workflow":12};
const byName=new Map(map.entities.map(e=>[e.sourceEntity,e]));

test('inventory and exact field counts cover all 79',()=>{assert.deepEqual([...byName.keys()].sort(),expected);assert.equal(Object.keys(expectedCounts).length,79);for(const [n,count] of Object.entries(expectedCounts)){const e=byName.get(n);assert.equal(e.reviewedSourceFieldCount,count,n);assert.equal(e.sourceFieldAudit.declaredFieldPaths.length,count,n);}});
test('seven pinned current-main fixtures have exact counts and blob SHAs',()=>{const expected={AirmanReleaseMonitor:8,ApiKey:14,ApiRequestLog:7,BillOfSaleDraft:37,EngineMaintenance:19,PreBuyInspection:81,SkillDefinition:19};assert.deepEqual(Object.fromEntries(Object.entries(map.sourceSchemaAudit.pinnedCurrentMainFixtures).map(([n,v])=>[n,v.expectedFieldCount])),expected);for(const [n,v] of Object.entries(map.sourceSchemaAudit.pinnedCurrentMainFixtures)){assert.match(v.blobSha,/^[0-9a-f]{40}$/);assert.equal(byName.get(n).reviewedSourceFieldCount,v.expectedFieldCount);}});
test('every declared field is auditable and fully partitioned',()=>{for(const e of map.entities){const a=e.sourceFieldAudit;assert.equal(new Set(a.declaredFieldPaths).size,a.declaredFieldPaths.length,e.sourceEntity);const sensitive=new Set(a.sensitiveFieldPaths),non=new Set(a.reviewedNonSensitiveFieldPaths);for(const p of sensitive)assert.ok(!non.has(p),e.sourceEntity+': '+p);assert.deepEqual([...new Set([...sensitive,...non])].sort(),[...a.declaredFieldPaths].sort(),e.sourceEntity);const hash=crypto.createHash('sha256').update([...a.declaredFieldPaths].sort().join('\n')).digest('hex');assert.equal(a.pathSetSha256,hash,e.sourceEntity);const categorized=new Set(Object.values(e.sensitiveFieldEvidence).flat());assert.deepEqual([...categorized].sort(),[...sensitive].sort(),e.sourceEntity);}});
test('all relationType declarations are represented exactly once',()=>{const count=map.entities.reduce((n,e)=>n+e.sourceRelationAudit.length,0);assert.equal(count,43);assert.equal(map.sourceSchemaAudit.relationCount,43);for(const e of map.entities){const keys=e.sourceRelationAudit.map(r=>r.fieldPath+'>'+r.targetEntity);assert.equal(new Set(keys).size,keys.length,e.sourceEntity);for(const r of e.sourceRelationAudit){assert.ok(r.fieldPath);assert.ok(byName.has(r.targetEntity),e.sourceEntity+' -> '+r.targetEntity);assert.equal(typeof r.declaredRequired,'boolean');assert.match(r.evidence,/relationType=/);}}});
test('declared required status reconciles to mandatory or optional dependency',()=>{for(const e of map.entities)for(const r of e.sourceRelationAudit){const mandatory=e.mandatoryDependencies.find(d=>d.kind==='entity'&&d.fieldPath===r.fieldPath&&d.target===r.targetEntity);const optional=e.optionalDependencies.find(d=>d.kind==='entity'&&d.fieldPath===r.fieldPath&&d.target===r.targetEntity);if(r.declaredRequired){assert.ok(mandatory,e.sourceEntity+': '+r.fieldPath);assert.ok(!optional);}else if(e.sourceEntity==='SalesPipeline'&&r.fieldPath==='passport_id'){assert.ok(mandatory);assert.equal(mandatory.basis,'semantic_required_upgrade');assert.equal(mandatory.sourceDeclaredRequired,false);assert.ok(!optional);}else{assert.ok(optional,e.sourceEntity+': '+r.fieldPath);assert.ok(!mandatory);}}});
test('architect-specified relation omissions are fixed',()=>{const dep=(n,status,target)=>byName.get(n)[status+'Dependencies'].some(d=>d.target===target);assert.ok(dep('ATICard','mandatory','AircraftListing'));assert.ok(dep('EditorProfile','mandatory','AircraftListing'));assert.ok(dep('OwnershipTrace','mandatory','AircraftListing'));assert.ok(dep('ExpertValuation','mandatory','AircraftListing'));for(const t of ['ATICard','AircraftListing'])assert.ok(dep('AffiliateLink','optional',t));assert.ok(dep('BrokerAlert','optional','DealerLocation'));for(const t of ['EscrowTransaction','Settlement','PartnerConfig'])assert.ok(dep('CommissionLedger','optional',t));for(const t of ['ATICard','AffiliateLink'])assert.ok(dep('LeadEvent','optional',t));assert.ok(dep('ReportRequest','optional','ATIPassport'));assert.ok(dep('SalesPipeline','mandatory','ATIPassport'));assert.ok(dep('SalesPipeline','optional','AircraftListing'));assert.ok(dep('VaultDocument','optional','AircraftListing'));});
test('canonical Aircraft dependencies remain distinct from source relations',()=>{assert.ok(byName.get('AircraftListing').mandatoryDependencies.some(d=>d.kind==='concept'&&d.target==='Aircraft'));assert.ok(!byName.get('AircraftListing').mandatoryDependencies.some(d=>d.target==='FAAAircraft'));assert.ok(byName.get('ATIPassport').optionalDependencies.some(d=>d.target==='AircraftListing'));});
test('sensitivity regressions are fixed from exact source paths',()=>{const has=(n,c,p)=>byName.get(n).sensitiveFieldEvidence[c]?.includes(p);assert.ok(has('PartnerConfig','credentials_and_security','embed_token'));assert.ok(has('TrafficSnapshot','free_text_or_unstructured','aircraft_json'));assert.ok(has('TrafficSnapshot','direct_pii','refreshed_by'));for(const p of ['model_omvm','expert_omvm','delta_pct'])assert.ok(has('ExpertValuation','financial_and_entitlement',p));for(const p of ['rationale','factors_tagged'])assert.ok(has('ExpertValuation','free_text_or_unstructured',p));for(const p of ['purchaser_apt_suite','faa_registered_owner','registration_applicant_name'])assert.ok(has('BillOfSaleDraft','direct_pii',p));for(const p of ['input_schema','output_schema','data_sources','function_name'])assert.ok(has('SkillDefinition','executable_or_agent_configuration',p));});
test('PreBuy nested evidence and IDs are classified exhaustively',()=>{const e=byName.get('PreBuyInspection');for(const p of ['buyer.id','inspector.id','participants[].id','checklist[].id','findings[].id','audit_history[].actor_id','inspector_signature.user_id'])assert.ok(e.sensitiveFieldEvidence.pseudonymous_or_internal_identifier.includes(p),p);for(const p of ['checklist[].evidence_urls','findings[].media_urls','findings[].document_urls','inspector_signature.certificate'])assert.ok(e.sensitiveFieldEvidence.confidential_document_or_evidence.includes(p),p);for(const p of ['checklist[].notes','findings[].inspector_comments','findings[].seller_response','findings[].buyer_notes','audit_history[].details'])assert.ok(e.sensitiveFieldEvidence.free_text_or_unstructured.includes(p),p);});
test('prior security and lifecycle controls remain present',()=>{assert.equal(map.issueDomainCatalog.length,15);assert.equal(map.boundaries.defaultAccess,'deny');assert.match(map.credentialAndLoggingPolicy.apiKeys.storage,/hash only/);assert.ok(map.publicDtos.ATICard.allowlist.length);assert.ok(map.publicDtos.AircraftListing.allowlist.length);assert.equal(map.publicIdentityLifecycle.reuse,'never');assert.match(map.dataGovernance.backups,/re-erasure/);assert.equal(map.boundaries.noMigrationSql,true);assert.equal(map.boundaries.noProductionMutation,true);});
test('artifact has no migration SQL',()=>assert.doesNotMatch(JSON.stringify(map),/CREATE\s+TABLE|ALTER\s+TABLE|DROP\s+TABLE|INSERT\s+INTO/i));


test('no entity has the same dependency target in mandatory and optional sets',()=>{for(const e of map.entities){const mandatory=new Set(e.mandatoryDependencies.map(d=>d.target));const overlap=[...new Set(e.optionalDependencies.map(d=>d.target))].filter(t=>mandatory.has(t));assert.deepEqual(overlap,[],e.sourceEntity);assert.equal(new Set(e.mandatoryDependencies.map(d=>d.kind+':'+d.target)).size,e.mandatoryDependencies.length,e.sourceEntity+' mandatory duplicates');assert.equal(new Set(e.optionalDependencies.map(d=>d.kind+':'+d.target)).size,e.optionalDependencies.length,e.sourceEntity+' optional duplicates');}});

test('final architect high-risk paths are classified and not reviewed non-sensitive',()=>{const cases={ATICardReview:{direct_pii:['reviewer_name'],free_text_or_unstructured:['comment']},ATIPassport:{confidential_document_or_evidence:['pdf_url','agreement_doc_url']},ATIVerifyDocument:{direct_pii:['extracted_name']},AccountDeletion:{direct_pii:['user_name']},AircraftListing:{pseudonymous_or_internal_identifier:['owner']},DealerLocation:{direct_pii:['address','zip_code']},AviationService:{direct_pii:['address']},EscrowTransaction:{direct_pii:['buyer_name','broker_name']},ExpertCrossCheck:{direct_pii:['requester_name','expert_name'],free_text_or_unstructured:['expert_comment']},MarketComparable:{free_text_or_unstructured:['raw_listings']},PartnerListingFeed:{free_text_or_unstructured:['raw_payload']},ToolInvocation:{free_text_or_unstructured:['request_payload','response_payload'],financial_and_entitlement:['platform_revenue','developer_revenue']}};for(const [entity,categories] of Object.entries(cases)){const e=byName.get(entity);for(const [category,paths] of Object.entries(categories))for(const path of paths){assert.ok(e.sensitiveFieldEvidence[category].includes(path),entity+': '+path);assert.ok(e.sourceFieldAudit.sensitiveFieldPaths.includes(path),entity+': '+path);assert.ok(!e.sourceFieldAudit.reviewedNonSensitiveFieldPaths.includes(path),entity+': '+path);}}});

test('transaction, ownership, inspection and ATI evidence has regulatory flags',()=>{const expected={BillOfSaleDraft:['transaction_evidence','ownership_evidence'],OwnershipTrace:['ownership_evidence','transaction_evidence'],PreBuyInspection:['inspection_evidence','airworthiness_evidence'],BrokerAgreement:['transaction_evidence','ownership_evidence'],VaultDocument:['document_evidence','transaction_evidence'],ATIPassport:['ownership_verification_evidence'],ATICard:['ownership_verification_evidence'],ATICardReview:['verification_evidence'],ATIVerifySession:['verification_evidence'],ATIVerifyDocument:['verification_evidence','identity_document_evidence'],ATIVerifyScore:['verification_evidence']};for(const [entity,flags] of Object.entries(expected)){const actual=byName.get(entity).regulatoryFlags;assert.ok(actual.length,entity);for(const flag of flags)assert.ok(actual.includes(flag),entity+': '+flag);}});
