import { ChevronDown, ExternalLink } from "lucide-react";
import StatusBadge from "@/components/protocol/StatusBadge";
import { RFC_STATUS } from "@/components/protocol/protocolData";

export default function RfcRow({ rfc, expanded, isAdmin, saving, onToggle, onStatus, onOpenSpec }) {
  const date = rfc.created_date ? new Intl.DateTimeFormat("en", { dateStyle: "medium" }).format(new Date(rfc.created_date)) : "—";
  return (
    <article className="border-b border-white/[0.08] last:border-0">
      <div className="flex flex-col gap-3 p-4 sm:flex-row sm:items-center"><button onClick={onToggle} aria-expanded={expanded} className="flex min-h-11 min-w-0 flex-1 items-center gap-3 text-left focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[#f5c242]"><ChevronDown className={`h-4 w-4 shrink-0 text-white/40 transition-transform duration-200 ${expanded ? "rotate-180" : ""}`} /><span className="w-16 shrink-0 font-mono text-xs font-bold text-[#f5c242]">{rfc.rfc_id}</span><span className="min-w-0 flex-1 truncate text-sm font-bold text-white">{rfc.title}</span></button><div className="flex items-center gap-3 pl-7 sm:pl-0"><StatusBadge status={rfc.status} />{isAdmin ? <select aria-label={`Status for ${rfc.rfc_id}`} disabled={saving} value={rfc.status} onChange={(e) => onStatus(e.target.value)} className="h-11 rounded-lg border px-2 text-xs disabled:opacity-50">{Object.entries(RFC_STATUS).map(([value, [label]]) => <option key={value} value={value}>{label}</option>)}</select> : null}</div><span className="hidden w-28 text-xs text-white/45 lg:block">{rfc.author}</span><span className="hidden w-24 text-right text-xs text-white/35 xl:block">{date}</span></div>
      {expanded && <div className="bg-white/[0.025] px-5 py-5 sm:px-12"><div className="grid gap-5 md:grid-cols-2"><section><h4 className="text-[10px] font-bold uppercase tracking-[0.16em] text-white/40">Abstract</h4><p className="mt-2 text-sm leading-6 text-white/70">{rfc.abstract || "No abstract available."}</p></section><section><h4 className="text-[10px] font-bold uppercase tracking-[0.16em] text-white/40">Motivation</h4><p className="mt-2 text-sm leading-6 text-white/70">{rfc.motivation || "No motivation available."}</p></section></div><button onClick={() => onOpenSpec(rfc.category)} className="mt-5 inline-flex min-h-11 items-center gap-2 text-xs font-bold text-[#f5c242] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[#f5c242]"><ExternalLink className="h-3.5 w-3.5" />View protocol specification</button></div>}
    </article>
  );
}