name: Cloudflare Pages

on:
  pull_request:
    branches:
      - abos-factory/v1
    paths:
      - ".github/workflows/deploy-cloudflare-pages.yml"
      - "package.json"
      - "package-lock.json"
      - "vite.config.*"
      - "src/**"
  workflow_dispatch:

permissions